# Generated by Django 4.2.16 on 2025-02-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('weight', '0003_auto_20160416_1030'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='weightentry',
        #     unique_together=set(),
        # ),
        migrations.AlterField(
            model_name='weightentry',
            name='date',
            field=models.DateTimeField(verbose_name='Date'),
        ),
    ]
