# Generated by Django 5.2.7 on 2025-10-21 10:11

import uuid
from django.db import migrations, models


def gen_uuids(apps, schema_editor):
    WeightEntry = apps.get_model('weight', 'WeightEntry')

    for entry in WeightEntry.objects.all():
        entry.uuid = uuid.uuid4()
        entry.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('weight', '0004_multiple_weight_entries_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Generate UUIDs
        migrations.RunPython(
            gen_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        # Set uuid fields to non-nullable
        migrations.AlterField(
            model_name='weightentry',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=True, null=False),
        ),
    ]
