# Generated by Django 5.2.7 on 2025-10-21 10:11

from django.db import migrations, models
from django.db.migrations.state import StateApps

from wger.utils.db import backfill_uuid_column
from wger.utils.uuid import uuid7


def gen_uuids(apps: StateApps, schema_editor):
    backfill_uuid_column(apps.get_model('weight', 'WeightEntry'))


class Migration(migrations.Migration):
    dependencies = [
        ('weight', '0004_multiple_weight_entries_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='uuid',
            field=models.UUIDField(default=uuid7, editable=False, null=True),
        ),
        # Generate UUIDs
        migrations.RunPython(
            gen_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        # Set uuid fields to non-nullable and unique
        migrations.AlterField(
            model_name='weightentry',
            name='uuid',
            field=models.UUIDField(default=uuid7, editable=True, null=False, unique=True),
        ),
    ]
