# Generated by Django 5.2.7 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('weight', '0005_add_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightentry',
            name='weight_unit',
            field=models.CharField(
                choices=[('kg', 'Kilogram'), ('lb', 'Pound')],
                default='kg',
                max_length=2,
                verbose_name='Weight unit',
            ),
        ),
    ]
