version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: wger
      POSTGRES_USER: wger
      POSTGRES_PASSWORD: wger
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  web:
    build:
      context: ./extras/docker/production
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: wger
      POSTGRES_USER: wger
      POSTGRES_PASSWORD: wger
      POSTGRES_HOST: db
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SETTINGS_MODULE: wger.settings.production
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  db_data: