-- CREATE TABLE "exercises_exercise" (
--     "id" integer NOT NULL PRIMARY KEY,
--     "category_id" integer NOT NULL REFERENCES "exercises_exercisecategory" ("id"),
--     "description" varchar(2000) NOT NULL,
--     "name" varchar(200) NOT NULL UNIQUE
-- )

INSERT INTO "exercises_exercise" VALUES(1,1,'','Trizeps Seildrücken');
INSERT INTO "exercises_exercise" VALUES(2,1,'','Curls');
INSERT INTO "exercises_exercise" VALUES(3,1,'','Bizeps am Kabel');
INSERT INTO "exercises_exercise" VALUES(4,4,'','Crunches');
INSERT INTO "exercises_exercise" VALUES(5,2,'','Ausfallschritte im Gehen');
INSERT INTO "exercises_exercise" VALUES(6,2,'','Beinpresse');
INSERT INTO "exercises_exercise" VALUES(7,2,'','Kniebeuge');
INSERT INTO "exercises_exercise" VALUES(8,5,'','Shrugs');
INSERT INTO "exercises_exercise" VALUES(9,3,'','Kreuzheben');
INSERT INTO "exercises_exercise" VALUES(10,3,'','Frontziehen breit');
INSERT INTO "exercises_exercise" VALUES(11,3,'','Einarmiges rudern KH');
INSERT INTO "exercises_exercise" VALUES(12,3,'','Frontziehen eng');
INSERT INTO "exercises_exercise" VALUES(13,6,'','Wadenheben stehend');
INSERT INTO "exercises_exercise" VALUES(14,6,'','Wadenheben sitzend');
INSERT INTO "exercises_exercise" VALUES(15,7,'','Bankdrücken LH');
INSERT INTO "exercises_exercise" VALUES(16,7,'','Schrägbankdrücken KH');
INSERT INTO "exercises_exercise" VALUES(17,7,'','Negativ Bankdrücken');
INSERT INTO "exercises_exercise" VALUES(18,7,'','Fliegende KH Flachbank');
INSERT INTO "exercises_exercise" VALUES(19,5,'','Frontdrücken KH');
INSERT INTO "exercises_exercise" VALUES(20,5,'','Seitheben KH');
INSERT INTO "exercises_exercise" VALUES(21,5,'','Butterfly reverse');
INSERT INTO "exercises_exercise" VALUES(22,2,'','Beinbeuger liegend');
INSERT INTO "exercises_exercise" VALUES(23,6,'','Hackenschmidt');
INSERT INTO "exercises_exercise" VALUES(24,1,'','Bizeps LH-Curls');
INSERT INTO "exercises_exercise" VALUES(25,1,'','Frenchpress ß-Stange');
INSERT INTO "exercises_exercise" VALUES(26,1,'','Bizeps KH-Curls');
INSERT INTO "exercises_exercise" VALUES(27,1,'','Trizepsmaschine');
INSERT INTO "exercises_exercise" VALUES(28,1,'','KH an Scottmaschine');
INSERT INTO "exercises_exercise" VALUES(29,1,'','Dips');
INSERT INTO "exercises_exercise" VALUES(30,7,'','Butterfly');
INSERT INTO "exercises_exercise" VALUES(31,7,'','Umsetzen');
INSERT INTO "exercises_exercise" VALUES(32,4,'','Crunches an Negativbank');
INSERT INTO "exercises_exercise" VALUES(33,4,'','Crunches am Seil');
INSERT INTO "exercises_exercise" VALUES(34,4,'','Beinheben liegend');
INSERT INTO "exercises_exercise" VALUES(35,4,'','Beinheben aufrecht');
INSERT INTO "exercises_exercise" VALUES(36,3,'','Klimmzüge');
INSERT INTO "exercises_exercise" VALUES(37,3,'','Long-Pulley');
INSERT INTO "exercises_exercise" VALUES(38,1,'','Bankdrücken eng');
INSERT INTO "exercises_exercise" VALUES(39,2,'','Beinstrecker');
INSERT INTO "exercises_exercise" VALUES(40,7,'','Überzugmaschine');
INSERT INTO "exercises_exercise" VALUES(41,7,'','Schrägbankdrücken LH');
INSERT INTO "exercises_exercise" VALUES(42,5,'','Rudern aufgelegt');
INSERT INTO "exercises_exercise" VALUES(43,5,'','Nackenziehen');
INSERT INTO "exercises_exercise" VALUES(44,1,'','Bizeps Cursl mit ß-Stange ');
INSERT INTO "exercises_exercise" VALUES(45,1,'','Trizepsdrücken KH über Kopf');
INSERT INTO "exercises_exercise" VALUES(46,1,'','Hammercurls');
INSERT INTO "exercises_exercise" VALUES(47,5,'','Vorgebeugtes Seitheben');
INSERT INTO "exercises_exercise" VALUES(48,3,'','Klimmzüge an Maschine');
INSERT INTO "exercises_exercise" VALUES(49,3,'','MGM-Maschine');
INSERT INTO "exercises_exercise" VALUES(50,3,'','Good Mornings');
INSERT INTO "exercises_exercise" VALUES(51,4,'','Crunches an Maschine');
INSERT INTO "exercises_exercise" VALUES(52,7,'','Butterfly eng');
INSERT INTO "exercises_exercise" VALUES(53,5,'','Schultermaschine');
INSERT INTO "exercises_exercise" VALUES(54,2,'','Beinpresse eng');
INSERT INTO "exercises_exercise" VALUES(55,2,'','Ausfallschritte stehend');
INSERT INTO "exercises_exercise" VALUES(56,4,'','Crunches am Stuhl');
INSERT INTO "exercises_exercise" VALUES(57,4,'','Sit Ups');
INSERT INTO "exercises_exercise" VALUES(58,1,'','Frenchpress KH');
INSERT INTO "exercises_exercise" VALUES(59,3,'','Rudern vorgebeugt LH');
INSERT INTO "exercises_exercise" VALUES(60,3,'','Hyperextensions');
INSERT INTO "exercises_exercise" VALUES(61,3,'','Schrägbankdrücken MP');
INSERT INTO "exercises_exercise" VALUES(62,5,'','Rudern aufrecht ß-Stange');
INSERT INTO "exercises_exercise" VALUES(63,1,'','Trizeps Seildrücken mit Stange');
INSERT INTO "exercises_exercise" VALUES(64,2,'','Rumpfbeugen');
INSERT INTO "exercises_exercise" VALUES(65,5,'','Frontheben am Kabel');
INSERT INTO "exercises_exercise" VALUES(66,5,'','Schulterdrücken MP');
INSERT INTO "exercises_exercise" VALUES(67,5,'','Schulterheben MP');
INSERT INTO "exercises_exercise" VALUES(68,1,'','Dips zwischen 2 Bänke');
INSERT INTO "exercises_exercise" VALUES(69,2,'','Beinstrecker einbeinig');
INSERT INTO "exercises_exercise" VALUES(70,3,'','Rudern vorgebeugt LH reverse');
INSERT INTO "exercises_exercise" VALUES(71,7,'','Kabelcross');
INSERT INTO "exercises_exercise" VALUES(72,2,'','Beinbeuger stehend');
INSERT INTO "exercises_exercise" VALUES(73,7,'','Fliegende KH Schrägbank');
