# Generated by Django 4.1.7 on 2023-03-24 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('config', '0002_auto_20190618_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanguageConfig',
        ),
    ]
