# Generated by Django 3.1.3 on 2020-12-03 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0005_auto_20190618_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='variations',
            field=models.ForeignKey(
                default='',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='exercises.variation',
                verbose_name='Variations',
            ),
        ),
    ]
