# Generated by Django 3.1.3 on 2020-12-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_auto_20190618_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='_exercise_variations_+', to='exercises.Exercise', verbose_name='Variations'),
        ),
    ]
