# Generated by Django 3.1.4 on 2020-12-11 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0009_auto_20201211_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscles',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscles_secondary',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='variations',
        ),
    ]
