# Generated by Django 3.1.3 on 2020-12-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20201201_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='variation',
        ),
        migrations.AddField(
            model_name='exercise',
            name='variations',
            field=models.ManyToManyField(blank=True, to='exercises.ExerciseVariation', verbose_name='Variations'),
        ),
    ]
