# Generated by Django 3.1.3 on 2020-12-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_auto_20201201_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseVariation',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='_exercise_variations_+', to='exercises.Exercise', verbose_name='Variations'),
        ),
    ]
