# Generated by Django 3.2 on 2021-05-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0012_auto_20210327_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseimage',
            old_name='exercise',
            new_name='exercise_base',
        ),
        migrations.AlterField(
            model_name='exercisebase',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source '
                'here. This is needed for some licenses e.g. the '
                'CC-BY-SA.',
                max_length=50,
                null=True,
                verbose_name='Author',
            ),
        ),
        migrations.AlterField(
            model_name='exercisebase',
            name='variations',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='exercises.variation',
                verbose_name='Variations',
            ),
        ),
    ]
