# Generated by Django 3.2.7 on 2021-09-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0013_auto_20210503_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseimage',
            name='style',
            field=models.CharField(
                choices=[
                    ('1', 'Line'),
                    ('2', '3D'),
                    ('3', 'Low-poly'),
                    ('4', 'Photo'),
                    ('5', 'Other'),
                ],
                default='1',
                help_text='The art style of your image',
                max_length=1,
            ),
        ),
    ]
