# Generated by Django 3.2.10 on 2022-01-20 21:27

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wger.exercises.models.video


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210726_1729'),
        ('exercises', '0014_exerciseimage_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseimage',
            name='style',
            field=models.CharField(choices=[('1', 'Line'), ('2', '3D'), ('3', 'Low-poly'), ('4', 'Photo'), ('5', 'Other')], default='4', help_text='The art style of your image', max_length=1),
        ),
        migrations.CreateModel(
            name='ExerciseVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_author', models.CharField(blank=True, help_text='If you are not the author, enter the name or source here. This is needed for some licenses e.g. the CC-BY-SA.', max_length=50, null=True, verbose_name='Author')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('video', models.FileField(upload_to=wger.exercises.models.video.exercise_video_upload_dir, verbose_name='Video')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main video')),
                ('exercise_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercisebase', verbose_name='Exercise')),
                ('license', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.license', verbose_name='License')),
            ],
            options={
                'ordering': ['-is_main', 'id'],
            },
        ),
    ]
