# Generated by Django 3.2.10 on 2022-02-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0015_exercise_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('alias', models.CharField(max_length=200, verbose_name='Alias for an exercise')),
                (
                    'exercise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='exercises.exercise',
                        verbose_name='Exercise',
                    ),
                ),
            ],
        ),
    ]
