# Generated by Django 3.2.9 on 2021-11-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_exerciseimage_style'),
        ('exercises', '0016_auto_20210912_1231'),
    ]

    operations = [
    ]
