# Generated by Django 3.2.13 on 2022-05-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0016_exercisealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='muscle',
            name='name_en',
            field=models.CharField(default='', max_length=50),
        ),
    ]
