# Generated by Django 3.2.10 on 2022-02-19 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_auto_20220218_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='name_original',
        ),
        migrations.RemoveField(
            model_name='historicalexercise',
            name='name_original',
        ),
        migrations.AddField(
            model_name='exercise',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='historicalexercise',
            name='update_date',
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Date'
            ),
            preserve_default=False,
        ),
    ]
