# Generated by Django 3.2.10 on 2022-03-02 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def delete_pending_exercises(apps, schema_editor):
        """
        Delete all pending exercises

        Note that we can't access STATUS_PENDING here because we are not using
        a real model.
        """
        Exercise = apps.get_model("exercises", "Exercise")
        Exercise.objects.filter(status='1').delete()

    dependencies = [
        ('exercises', '0018_auto_20220219_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisecomment',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='historicalexercisecomment',
            name='exercise',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exercises.exercise', verbose_name='Exercise'),
        ),
        migrations.RunPython(delete_pending_exercises),
    ]
