# Generated by Django 3.2.10 on 2022-03-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_auto_20220302_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='status',
        ),
        migrations.RemoveField(
            model_name='exercisebase',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalexercise',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalexercisebase',
            name='status',
        ),
    ]
