# Generated by Django 4.0.8 on 2023-01-23 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0020_historicalexerciseimage_historicalexercisevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'model_type',
                    models.CharField(
                        choices=[
                            ('base', 'base'),
                            ('translation', 'translation'),
                            ('image', 'image'),
                            ('video', 'video'),
                        ],
                        max_length=11,
                    ),
                ),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
