# Generated by Django 3.2.10 on 2022-05-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0017_muscle_name_en'),
        ('exercises', '0020_auto_20220302_2136'),
    ]

    operations = [
    ]
