# Generated by Django 3.2.13 on 2022-05-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0021_merge_0017_muscle_name_en_0020_auto_20220302_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalalias',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical alias',
                'verbose_name_plural': 'historical aliass'
            },
        ),
        migrations.AlterModelOptions(
            name='historicalexercise',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical exercise',
                'verbose_name_plural': 'historical exercises'
            },
        ),
        migrations.AlterModelOptions(
            name='historicalexercisebase',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical exercise base',
                'verbose_name_plural': 'historical exercise bases'
            },
        ),
        migrations.AlterModelOptions(
            name='historicalexercisecomment',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical exercise comment',
                'verbose_name_plural': 'historical exercise comments'
            },
        ),
        migrations.AlterField(
            model_name='historicalalias',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalexercisebase',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalexercisecomment',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
