# Generated by Django 4.1.5 on 2023-03-17 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0022_alter_exercise_license_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionlog',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'
            ),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'
            ),
        ),
        migrations.AlterField(
            model_name='exercisebase',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'
            ),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'
            ),
        ),
        migrations.AlterField(
            model_name='exercisevideo',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercisebase',
            name='uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'
            ),
        ),
        migrations.AlterField(
            model_name='historicalexerciseimage',
            name='uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercisevideo',
            name='uuid',
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'
            ),
        ),
    ]
