# Generated by Django 4.1.9 on 2023-10-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0025_rename_update_date_exercise_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionlog',
            name='replaced_by',
            field=models.UUIDField(
                default=None,
                editable=False,
                help_text='UUID of the object ',
                null=True,
                verbose_name='Replaced by',
            ),
        ),
    ]
