# Generated by Django 4.2.6 on 2024-01-06 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0028_add_uuid_alias_and_comments"),
    ]

    operations = [

        migrations.RenameModel(
            "Exercise",
            "Translation"
        ),
        migrations.RenameModel(
            old_name='HistoricalExercise',
            new_name='HistoricalTranslation',
        ),
        migrations.AlterModelOptions(
            name='historicaltranslation',
            options={'get_latest_by': ('history_date', 'history_id'),
                     'ordering': ('-history_date', '-history_id'),
                     'verbose_name': 'historical translation',
                     'verbose_name_plural': 'historical translations'},
        ),
        migrations.AlterModelTable(
            name='translation',
            table='exercises_exercise',
        ),
    ]
