# Generated by Django 4.2.6 on 2024-01-18 16:55

import django.contrib.postgres.search
from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0028_add_uuid_alias_and_comments'),
    ]

    operations = [
        BtreeGinExtension(),
        TrigramExtension(),
        migrations.AddIndex(
            model_name='exercise',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['name'],
                name='exercises_e_name_ac11f4_gin',
            ),
        ),
        migrations.AddIndex(
            model_name='alias',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['alias'], name='exercises_a_alias_227e38_gin'
            ),
        ),
    ]
