# Generated by Django 4.2.6 on 2024-05-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0029_full_text_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='exercisebase',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='exercisevideo',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercisebase',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexerciseimage',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercisevideo',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
    ]
