# Generated by Django 4.2.13 on 2024-06-12 12:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0030_increase_author_field_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='Translation',
        ),
        migrations.RenameModel(
            old_name='HistoricalExercise',
            new_name='HistoricalTranslation',
        ),
    ]
