# Generated by Django 4.2.13 on 2025-01-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0030_increase_author_field_length'),
        ('manager', '0017_alter_workoutlog_exercise_base'),
    ]

    operations = [
        # Rename exercise base to exercise and exercise to translation
        migrations.RenameModel(
            old_name='Exercise',
            new_name='Translation',
        ),
        migrations.RenameModel(
            old_name='HistoricalExercise',
            new_name='HistoricalTranslation',
        ),
        migrations.RenameModel(
            old_name='ExerciseBase',
            new_name='Exercise',
        ),
        migrations.RenameModel(
            old_name='HistoricalExerciseBase',
            new_name='HistoricalExercise',
        ),
        migrations.AlterModelOptions(
            name='historicalexercise',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical exercise',
                'verbose_name_plural': 'historical exercises',
            },
        ),
        migrations.AlterModelOptions(
            name='historicaltranslation',
            options={
                'get_latest_by': ('history_date', 'history_id'),
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical translation',
                'verbose_name_plural': 'historical translations',
            },
        ),
        # Rename exercise base foreign keys
        migrations.RenameField(
            model_name='exercisevideo',
            old_name='exercise_base',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='historicalexercisevideo',
            old_name='exercise_base',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='exerciseimage',
            old_name='exercise_base',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='historicalexerciseimage',
            old_name='exercise_base',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='exercise_base',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='historicaltranslation',
            old_name='exercise_base',
            new_name='exercise',
        ),
        migrations.RenameField(
            model_name='alias',
            old_name='exercise',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='historicalalias',
            old_name='exercise',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='exercisecomment',
            old_name='exercise',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='historicalexercisecomment',
            old_name='exercise',
            new_name='translation',
        ),
    ]
