# Generated by Django 5.2.7 on 2025-10-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0032_rename_exercise'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='translation',
            constraint=models.UniqueConstraint(
                fields=('exercise', 'language'),
                name='unique_exercise_language_translation',
                violation_error_message='A translation for this exercise and language already exists.',
            ),
        ),
    ]
