# Generated by Django 5.2.6 on 2025-10-02 06:32

import django.db.models.deletion
import wger.exercises.models.image
import wger.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0032_rename_exercise'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='translation',
            new_name='exercises_t_name_6264c9_gin',
            old_name='exercises_e_name_ac11f4_gin',
        ),
        migrations.AddField(
            model_name='exerciseimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='exerciseimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Width'),
        ),
        migrations.AddField(
            model_name='historicalexerciseimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='historicalexerciseimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='deletionlog',
            name='replaced_by',
            field=models.UUIDField(default=None, editable=False, help_text='UUID of the object replaced by the deleted one. At the moment only available for exercises', null=True, verbose_name='Replaced by'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='license_author',
            field=models.TextField(blank=True, help_text='If you are not the author, enter the name or source here.', max_length=3500, null=True, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='image',
            field=models.ImageField(height_field='height', help_text='Only PNG and JPEG formats are supported', upload_to=wger.exercises.models.image.exercise_image_upload_dir, validators=[wger.utils.images.validate_image_static_no_animation], verbose_name='Image', width_field='width'),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Main picture'),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='license_author',
            field=models.TextField(blank=True, help_text='If you are not the author, enter the name or source here.', max_length=3500, null=True, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='exercisevideo',
            name='license_author',
            field=models.TextField(blank=True, help_text='If you are not the author, enter the name or source here.', max_length=3500, null=True, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='license_author',
            field=models.TextField(blank=True, help_text='If you are not the author, enter the name or source here.', max_length=3500, null=True, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='historicalexerciseimage',
            name='image',
            field=models.TextField(help_text='Only PNG and JPEG formats are supported', max_length=100, validators=[wger.utils.images.validate_image_static_no_animation], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='historicalexerciseimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Main picture'),
        ),
        migrations.AlterField(
            model_name='historicalexerciseimage',
            name='license_author',
            field=models.TextField(blank=True, help_text='If you are not the author, enter the name or source here.', max_length=3500, null=True, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='historicalexercisevideo',
            name='license_author',
            field=models.TextField(blank=True, help_text='If you are not the author, enter the name or source here.', max_length=3500, null=True, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='exercise',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='license_author',
            field=models.TextField(blank=True, help_text='If you are not the author, enter the name or source here.', max_length=3500, null=True, verbose_name='Author(s)'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='license_author',
            field=models.TextField(blank=True, help_text='If you are not the author, enter the name or source here.', max_length=3500, null=True, verbose_name='Author(s)'),
        ),
    ]
