# Generated by Django 5.2.6 on 2025-10-02 06:20

from django.db import migrations


def update_image_dimensions(apps, schema_editor):
    ExerciseImage = apps.get_model('exercises', 'ExerciseImage')
    for image in ExerciseImage.objects.all():
        if image.image:
            try:
                image.width = image.image.width
                image.height = image.image.height
                image.save(update_fields=['width', 'height'])
            except FileNotFoundError:
                # Handle missing image files gracefully
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0033_rename_exercises_e_name_ac11f4_gin_exercises_t_name_6264c9_gin_and_more'),
    ]

    operations = [
        migrations.RunPython(update_image_dimensions, migrations.RunPython.noop),
    ]