# Generated manually

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0034_add_exercise_image_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseimage',
            name='is_ai_generated',
            field=models.BooleanField(
                default=False,
                verbose_name='AI Generated',
                help_text='Check if this image was generated by AI',
            ),
        ),
        migrations.AddField(
            model_name='historicalexerciseimage',
            name='is_ai_generated',
            field=models.BooleanField(
                default=False,
                verbose_name='AI Generated',
                help_text='Check if this image was generated by AI',
            ),
        ),
    ]
