# Generated by Django 5.2.9 on 2025-12-10 00:17

import django.db.models.deletion
import wger.exercises.models.image
import wger.utils.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0034_add_exercise_image_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltranslation',
            name='description_source',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Source)'),
        ),
        migrations.AddField(
            model_name='translation',
            name='description_source',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Source)'),
        ),
    ]
