# Generated by Django 5.2.9 on 2025-12-10 00:17

from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from markdownify import markdownify

from django.db import migrations, models

def migrate_description_to_markdown(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    Translation = apps.get_model('exercises', 'Translation')

    translations_to_migrate = Translation.objects.exclude(description='')
    for trans in translations_to_migrate:
        # ATX to ensure # headings instead of underlined headings.
        trans.description_source = markdownify(trans.description, heading_style='ATX')

        # save() triggers "description = render_markdown(description_source)". This
        # ensures a clean HTML cache
        trans.save()


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0034_add_exercise_image_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltranslation',
            name='description_source',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Source)'),
        ),
        migrations.AddField(
            model_name='translation',
            name='description_source',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Source)'),
        ),
        migrations.RunPython(migrate_description_to_markdown),
    ]
