# Generated by Django 5.2.13 on 2026-04-13 09:38

import django.db.models.deletion
import wger.exercises.models.image
import wger.utils.images
from django.db import migrations, models

"""
This migration has no real changes, it just re-syncs every change from the models
back, like help text changes and so.
"""


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0037_replace_variation_with_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deletionlog',
            name='replaced_by',
            field=models.UUIDField(
                default=None,
                editable=False,
                help_text='UUID of the object replaced by the deleted one. At the moment only available for exercises',
                null=True,
                verbose_name='Replaced by',
            ),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='license_author',
            field=models.TextField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='image',
            field=models.ImageField(
                height_field='height',
                help_text='Only JPEG, PNG and WebP formats are supported',
                upload_to=wger.exercises.models.image.exercise_image_upload_dir,
                validators=[wger.utils.images.validate_image_static_no_animation],
                verbose_name='Image',
                width_field='width',
            ),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main picture'),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='license_author',
            field=models.TextField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='exercisevideo',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main video'),
        ),
        migrations.AlterField(
            model_name='exercisevideo',
            name='license_author',
            field=models.TextField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='last_update',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='last update'),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='license_author',
            field=models.TextField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='variation_group',
            field=models.UUIDField(
                blank=True, db_index=True, null=True, verbose_name='Variation group'
            ),
        ),
        migrations.AlterField(
            model_name='historicalexerciseimage',
            name='image',
            field=models.TextField(
                help_text='Only JPEG, PNG and WebP formats are supported',
                max_length=100,
                validators=[wger.utils.images.validate_image_static_no_animation],
                verbose_name='Image',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexerciseimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main picture'),
        ),
        migrations.AlterField(
            model_name='historicalexerciseimage',
            name='license_author',
            field=models.TextField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercisevideo',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main video'),
        ),
        migrations.AlterField(
            model_name='historicalexercisevideo',
            name='license_author',
            field=models.TextField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='exercise',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='exercises.exercise',
            ),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='license_author',
            field=models.TextField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='translation',
            name='exercise',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='translations',
                to='exercises.exercise',
            ),
        ),
        migrations.AlterField(
            model_name='translation',
            name='license_author',
            field=models.TextField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
    ]
