# Generated by Django 5.2.12 on 2026-05-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0039_translation_alias_trigram_gin_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='license_author',
            field=models.TextField(
                blank=True,
                default='',
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='exerciseimage',
            name='license_author',
            field=models.TextField(
                blank=True,
                default='',
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='exercisevideo',
            name='license_author',
            field=models.TextField(
                blank=True,
                default='',
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='license_author',
            field=models.TextField(
                blank=True,
                default='',
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexerciseimage',
            name='license_author',
            field=models.TextField(
                blank=True,
                default='',
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicalexercisevideo',
            name='license_author',
            field=models.TextField(
                blank=True,
                default='',
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='license_author',
            field=models.TextField(
                blank=True,
                default='',
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='translation',
            name='license_author',
            field=models.TextField(
                blank=True,
                default='',
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                verbose_name='Author(s)',
            ),
        ),
    ]
