# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by Django 1.9.11 on 2017-01-18 22:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_auto_20170101_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
    ]
