# flake8: noqa
# Generated by Django 3.1 on 2020-08-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_auto_20170118_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritionplan',
            name='description',
            field=models.CharField(blank=True, help_text='A description of the goal of the plan, e.g. "Gain mass" or "Prepare for summer"', max_length=80, verbose_name='Description'),
        ),
    ]
