# Generated by Django 3.1.3 on 2021-01-02 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0007_auto_20201214_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='common_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='source_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='nutrition.nutritionplan',
                verbose_name='Nutrition plan',
            ),
        ),
    ]
