# Generated by Django 3.1.4 on 2020-12-12 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_auto_20201211_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='updated',
        ),
    ]
