# Generated by Django 3.2.6 on 2021-08-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0008_auto_20210102_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(
                blank=True,
                help_text='Give meals a textual description / name such as "Breakfast" or "after workout"',
                max_length=25,
                verbose_name='Name',
            ),
        ),
    ]
