# Generated by Django 3.2.7 on 2021-10-03 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0009_meal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitem',
            name='meal',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='log_items',
                to='nutrition.meal',
                verbose_name='Meal',
            ),
        ),
    ]
