# Generated by Django 3.2.7 on 2021-10-03 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_meal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='log_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='nutrition.logitem'),
        ),
    ]
