# Generated by Django 3.2.3 on 2021-10-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0009_auto_20210802_1526'),
        ('nutrition', '0009_meal_name'),
    ]

    operations = [
    ]
