# Generated by Django 3.2.12 on 2022-04-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_logitem_meal'),
        ('nutrition', '0010_merge_0009_auto_20210802_1526_0009_meal_name'),
    ]

    operations = [
    ]
