# Generated by Django 3.2.14 on 2022-08-09 12:33

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wger.nutrition.models.image
import wger.utils.helpers


def noop(apps, schema_editor):
    pass


def generate_uuids(apps, schema_editor):
    """
    Generate new UUIDs for each exercise
    :param apps:
    :param schema_editor:
    :return:
    """
    Ingredient = apps.get_model('nutrition', 'Ingredient')
    for ingredient in Ingredient.objects.all():
        ingredient.uuid = uuid.uuid4()
        ingredient.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_auto_20210726_1729'),
        ('nutrition', '0012_alter_ingredient_license_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                verbose_name='UUID',
            ),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'license_author',
                    models.CharField(
                        blank=True,
                        help_text='If you are not the author, enter the name or source here. This '
                        'is needed for some licenses e.g. the CC-BY-SA.',
                        max_length=60,
                        null=True,
                        verbose_name='Author',
                    ),
                ),
                (
                    'uuid',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name='UUID',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        help_text='Only PNG and JPEG formats are supported',
                        upload_to=wger.nutrition.models.image.ingredient_image_upload_dir,
                        verbose_name='Image',
                        height_field='height',
                        width_field='width',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('size', models.IntegerField()),
                ('height', models.IntegerField(editable=False)),
                ('width', models.IntegerField(editable=False)),
                (
                    'ingredient',
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='nutrition.ingredient',
                    ),
                ),
                (
                    'license',
                    models.ForeignKey(
                        default=2,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.license',
                        verbose_name='License',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, wger.utils.helpers.BaseImage),
        ),
        migrations.RunPython(generate_uuids, reverse_code=noop),
        migrations.AlterField(
            model_name='ingredient',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name='UUID',
            ),
        ),
    ]
