# Generated by Django 4.1.7 on 2023-06-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0014_license_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='update_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
    ]
