# Generated by Django 4.1.9 on 2023-09-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0017_remove_nutritionplan_language_alter_logitem_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='goal_carbohydrates',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='goal_energy',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='goal_fat',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='goal_protein',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
