# Generated by Django 4.2.6 on 2023-11-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0018_nutritionplan_goal_carbs_nutritionplan_goal_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=600,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='license_author_url',
            field=models.URLField(blank=True, verbose_name='Link to author profile, if available'),
        ),
        migrations.AlterField(
            model_name='image',
            name='license_derivative_source_url',
            field=models.URLField(
                blank=True,
                help_text='Note that a derivative work is one which is not only based on a previous work, but which also contains sufficient new, creative content to entitle it to its own copyright.',
                verbose_name='Link to the original source, if this is a derivative work',
            ),
        ),
        migrations.AlterField(
            model_name='image',
            name='license_object_url',
            field=models.URLField(blank=True, verbose_name='Link to original object, if available'),
        ),
        migrations.AlterField(
            model_name='image',
            name='license_title',
            field=models.CharField(
                blank=True,
                max_length=300,
                verbose_name='The original title of this object, if available',
            ),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=600,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='license_author_url',
            field=models.URLField(blank=True, verbose_name='Link to author profile, if available'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='license_derivative_source_url',
            field=models.URLField(
                blank=True,
                help_text='Note that a derivative work is one which is not only based on a previous work, but which also contains sufficient new, creative content to entitle it to its own copyright.',
                verbose_name='Link to the original source, if this is a derivative work',
            ),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='license_object_url',
            field=models.URLField(blank=True, verbose_name='Link to original object, if available'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='license_title',
            field=models.CharField(
                blank=True,
                max_length=300,
                verbose_name='The original title of this object, if available',
            ),
        ),
    ]
