# Generated by Django 3.2.15 on 2022-12-07 19:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0019_alter_image_license_author_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ingredient',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['name'], name='nutrition_i_search__f274b7_gin'
            ),
        ),
    ]
