# Generated by Django 4.2.6 on 2024-05-18 07:31

from django.db import migrations, models

from wger.nutrition.models import Source


def set_external_id(apps, schema_editor):
    """Set remote_id, used by imported ingredients (OFF, etc.)"""

    Ingredient = apps.get_model('nutrition', 'Ingredient')
    Ingredient.objects.filter(source_name=Source.OPEN_FOOD_FACTS.value).update(
        remote_id=models.F('code')
    )


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0021_add_fibers_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='remote_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.RunPython(
            set_external_id,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='image',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='license_author',
            field=models.CharField(
                blank=True,
                help_text='If you are not the author, enter the name or source here.',
                max_length=3500,
                null=True,
                verbose_name='Author(s)',
            ),
        ),
    ]
