# Generated by Django 4.2.6 on 2024-05-21 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0021_add_fibers_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='fibres',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fiber',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='In g per 100g of product', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Fiber'),
        ),
    ]
