# Generated by Django 4.2.6 on 2024-05-21 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0022_add_remote_id_increase_author_field_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='fibres',
            new_name='fiber',
        ),
        migrations.RenameField(
            model_name='nutritionplan',
            old_name='goal_fibers',
            new_name='goal_fiber',
        ),
    ]
