# Generated by Django 4.2.16 on 2025-02-22 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0024_remove_ingredient_status'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ingredient',
            new_name='nutrition_i_name_8f538f_gin',
            old_name='nutrition_i_search__f274b7_gin',
        ),
    ]
