# Generated by Django 4.2.13 on 2024-09-18 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def add_foreign_key(apps, schema_editor):
    Meal = apps.get_model('nutrition', 'Meal')
    MealItem = apps.get_model('nutrition', 'MealItem')
    Log = apps.get_model('nutrition', 'LogItem')

    for meal in Meal.objects.all():
        meal.user = meal.plan.user
        meal.save()

    for item in MealItem.objects.all():
        item.user = item.meal.plan.user
        item.save()

    for log in Log.objects.all():
        log.user = log.plan.user
        log.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nutrition', '0025_create_publication'),
    ]

    operations = [
        # Foreign key nullable
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(
                null=True,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='user',
            field=models.ForeignKey(
                null=True,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.AddField(
            model_name='logitem',
            name='user',
            field=models.ForeignKey(
                null=True,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        # Migrate
        migrations.RunPython(add_foreign_key, reverse_code=migrations.RunPython.noop),
        # Foreign key non nullable
        migrations.AlterField(
            model_name='meal',
            name='user',
            field=models.ForeignKey(
                null=False,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='user',
            field=models.ForeignKey(
                null=False,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='user',
            field=models.ForeignKey(
                null=False,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='User',
            ),
        ),
    ]
