# Generated by Django 5.2.5 on 2025-09-11 09:02

import datetime

from django.db import migrations, models


def copy_creation_date_to_start(apps, schema_editor):
    NutritionPlan = apps.get_model('nutrition', 'NutritionPlan')
    NutritionPlan.objects.all().update(start=models.F('creation_date'))


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0025_add_last_image_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='end',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='nutritionplan',
            name='start',
            field=models.DateField(default=datetime.date.today, verbose_name='Start date'),
        ),
        migrations.RunPython(
            copy_creation_date_to_start,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
