# Generated by Django 5.2.7 on 2025-12-05 17:50

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0027_prefill_end_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FastingWindow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start of fast"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End of fast"
                    ),
                ),
                (
                    "goal_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional target length for this fast.",
                        null=True,
                        verbose_name="Goal duration (minutes)",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=255, verbose_name="Notes"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fasting window",
                "verbose_name_plural": "Fasting windows",
                "ordering": ["-start"],
            },
        ),
        migrations.AlterModelOptions(
            name="nutritionplan",
            options={"ordering": ["-start"]},
        ),
        migrations.RenameIndex(
            model_name="ingredient",
            new_name="nutrition_i_name_8f538f_gin",
            old_name="nutrition_i_search__f274b7_gin",
        ),
        migrations.AlterField(
            model_name="nutritionplan",
            name="start",
            field=models.DateField(
                blank=True, default=datetime.date.today, verbose_name="Start date"
            ),
        ),
        migrations.AddField(
            model_name="fastingwindow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
