# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0027_prefill_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_vegan',
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text='Whether the ingredient is suitable for a vegan diet',
                null=True,
                verbose_name='Vegan',
            ),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_vegetarian',
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text='Whether the ingredient is suitable for a vegetarian diet',
                null=True,
                verbose_name='Vegetarian',
            ),
        ),
    ]
