# Generated by Django 4.2.16 on 2024-10-19 21:04

from django.db import migrations, models
import uuid


def gen_uuids(apps, schema_editor):
    NutritionPlan = apps.get_model('nutrition', 'NutritionPlan')
    Meal = apps.get_model('nutrition', 'Meal')
    MealItem = apps.get_model('nutrition', 'MealItem')
    LogItem = apps.get_model('nutrition', 'LogItem')

    for item in LogItem.objects.all():
        item.uuid = uuid.uuid4()
        item.save(update_fields=['uuid'])

    for item in MealItem.objects.all():
        item.uuid = uuid.uuid4()
        item.save(update_fields=['uuid'])

    for meal in Meal.objects.all():
        meal.uuid = uuid.uuid4()
        meal.save(update_fields=['uuid'])

    for plan in NutritionPlan.objects.all():
        plan.uuid = uuid.uuid4()
        plan.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0027_prefill_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionplan',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=False,
            ),
        ),
        migrations.AddField(
            model_name='meal',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=False,
            ),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=False,
            ),
        ),
        migrations.AddField(
            model_name='logitem',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=True,
                unique=False,
            ),
        ),
        # Generate UUIDs
        migrations.RunPython(
            gen_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        # Set uuid fields to non-nullable
        migrations.AlterField(
            model_name='nutritionplan',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='meal',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=False,
                unique=True,
            ),
        ),
    ]
