# Generated by Django 5.2.12 on 2026-03-17 14:16

# Django
from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0028_ingredient_dietary_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='nutriscore',
            field=models.CharField(
                blank=True,
                choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')],
                default=None,
                help_text='Nutri-Score grade from Open Food Facts',
                max_length=1,
                null=True,
                verbose_name='Nutri-Score',
            ),
        ),
    ]
