# Generated by Django 5.2.12 on 2026-03-26 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_add_unit_type_to_repetitionunit'),
        ('nutrition', '0029_ingredient_nutriscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionplan',
            options={'ordering': ['-start']},
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='start',
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                verbose_name='Start date',
            ),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(
                fields=['last_update'],
                name='idx_ingredient_last_update',
            ),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(
                fields=['last_imported'],
                name='idx_ingredient_last_imported',
            ),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(
                condition=models.Q(('is_vegan', True)),
                fields=['is_vegan'],
                name='idx_ingredient_vegan',
            ),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(
                condition=models.Q(('is_vegetarian', True)),
                fields=['is_vegetarian'],
                name='idx_ingredient_vegetarian',
            ),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(
                fields=['nutriscore'],
                name='idx_ingredient_nutriscore',
            ),
        ),
    ]
