# Generated by Django 4.2.16 on 2024-10-19 21:04
"""
Convert NutritionPlan, Meal, MealItem and LogItem to use UUID primary keys.

The migration runs in three logical phases:

1. Add a `uuid` field to all four tables and backfill it for existing rows.
2. Repoint each FK that targets one of these tables to a temporary `<name>_tmp`
   UUID column copied from the parent's uuid.
3. Promote each table's `uuid` to the primary key (drop the integer `id`,
   rename `uuid` -> `id`) and restore the FKs as ForeignKeys to the new PK.

Order matters: parents must be repointed before their children's `_tmp` columns
become FK columns, otherwise Django can't construct the FK.
"""

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.state import StateApps
from django.db.models import OuterRef, Subquery

from wger.utils.uuid import uuid7


def gen_uuids(apps: StateApps, schema_editor):
    NutritionPlan = apps.get_model('nutrition', 'NutritionPlan')
    Meal = apps.get_model('nutrition', 'Meal')
    MealItem = apps.get_model('nutrition', 'MealItem')
    LogItem = apps.get_model('nutrition', 'LogItem')

    for plan in NutritionPlan.objects.all():
        plan.uuid = uuid7()
        plan.save(update_fields=['uuid'])

    for meal in Meal.objects.all():
        meal.uuid = uuid7()
        meal.save(update_fields=['uuid'])

    for item in MealItem.objects.all():
        item.uuid = uuid7()
        item.save(update_fields=['uuid'])

    for item in LogItem.objects.all():
        item.uuid = uuid7()
        item.save(update_fields=['uuid'])


def populate_meal_plan_tmp(apps: StateApps, schema_editor):
    Meal = apps.get_model('nutrition', 'Meal')
    NutritionPlan = apps.get_model('nutrition', 'NutritionPlan')
    Meal.objects.update(
        plan_tmp=Subquery(
            NutritionPlan.objects.filter(id=OuterRef('plan')).values('uuid')[:1],
        )
    )


def populate_mealitem_meal_tmp(apps: StateApps, schema_editor):
    MealItem = apps.get_model('nutrition', 'MealItem')
    Meal = apps.get_model('nutrition', 'Meal')
    MealItem.objects.update(
        meal_tmp=Subquery(
            Meal.objects.filter(id=OuterRef('meal')).values('uuid')[:1],
        )
    )


def populate_logitem_plan_tmp(apps: StateApps, schema_editor):
    LogItem = apps.get_model('nutrition', 'LogItem')
    NutritionPlan = apps.get_model('nutrition', 'NutritionPlan')
    LogItem.objects.update(
        plan_tmp=Subquery(
            NutritionPlan.objects.filter(id=OuterRef('plan')).values('uuid')[:1],
        )
    )


def populate_logitem_meal_tmp(apps: StateApps, schema_editor):
    LogItem = apps.get_model('nutrition', 'LogItem')
    Meal = apps.get_model('nutrition', 'Meal')
    LogItem.objects.exclude(meal__isnull=True).update(
        meal_tmp=Subquery(
            Meal.objects.filter(id=OuterRef('meal')).values('uuid')[:1],
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ('nutrition', '0034_ingredient_trigram_gin_index'),
    ]

    operations = [
        # ------------------------------------------------------------------
        # 1. Add uuid columns and backfill them
        # ------------------------------------------------------------------
        migrations.AddField(
            model_name='nutritionplan',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='meal',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='logitem',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=True, unique=False),
        ),
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='nutritionplan',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='logitem',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=False, unique=True),
        ),
        # ------------------------------------------------------------------
        # 2. Repoint via a tmp column
        # ------------------------------------------------------------------
        migrations.AddField(
            model_name='meal',
            name='plan_tmp',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_meal_plan_tmp, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name='meal', name='plan'),

        migrations.AddField(
            model_name='mealitem',
            name='meal_tmp',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_mealitem_meal_tmp, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name='mealitem', name='meal'),

        migrations.AddField(
            model_name='logitem',
            name='plan_tmp',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_logitem_plan_tmp, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name='logitem', name='plan'),
        migrations.AddField(
            model_name='logitem',
            name='meal_tmp',
            field=models.UUIDField(editable=False, null=True, blank=True),
        ),
        migrations.RunPython(populate_logitem_meal_tmp, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name='logitem', name='meal'),

        # ------------------------------------------------------------------
        # 3. Promote uuid to primary key on every table
        # ------------------------------------------------------------------
        migrations.RemoveField(model_name='nutritionplan', name='id'),
        migrations.AlterField(
            model_name='nutritionplan',
            name='uuid',
            field=models.UUIDField(
                default=uuid7,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RemoveField(model_name='meal', name='id'),
        migrations.AlterField(
            model_name='meal',
            name='uuid',
            field=models.UUIDField(
                default=uuid7,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RemoveField(model_name='mealitem', name='id'),
        migrations.AlterField(
            model_name='mealitem',
            name='uuid',
            field=models.UUIDField(
                default=uuid7,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RemoveField(model_name='logitem', name='id'),
        migrations.AlterField(
            model_name='logitem',
            name='uuid',
            field=models.UUIDField(
                default=uuid7,
                primary_key=True,
                serialize=False,
            ),
        ),
        # ------------------------------------------------------------------
        # 4. Restore the FKs as ForeignKeys to the new UUID PKs
        # ------------------------------------------------------------------
        migrations.RenameField(model_name='meal', old_name='plan_tmp', new_name='plan'),
        migrations.AlterField(
            model_name='meal',
            name='plan',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to='nutrition.nutritionplan',
                verbose_name='Nutrition plan',
            ),
        ),
        migrations.RenameField(model_name='mealitem', old_name='meal_tmp', new_name='meal'),
        migrations.AlterField(
            model_name='mealitem',
            name='meal',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to='nutrition.meal',
                verbose_name='Nutrition plan',
            ),
        ),
        migrations.RenameField(model_name='logitem', old_name='plan_tmp', new_name='plan'),
        migrations.AlterField(
            model_name='logitem',
            name='plan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='nutrition.nutritionplan',
                verbose_name='Nutrition plan',
            ),
        ),
        migrations.RenameField(model_name='logitem', old_name='meal_tmp', new_name='meal'),
        migrations.AlterField(
            model_name='logitem',
            name='meal',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='log_items',
                to='nutrition.meal',
                verbose_name='Meal',
            ),
        ),
        # ------------------------------------------------------------------
        # 5. Rename uuid -> id on every table for canonical access
        # ------------------------------------------------------------------
        migrations.RenameField(model_name='nutritionplan', old_name='uuid', new_name='id'),
        migrations.RenameField(model_name='meal', old_name='uuid', new_name='id'),
        migrations.RenameField(model_name='mealitem', old_name='uuid', new_name='id'),
        migrations.RenameField(model_name='logitem', old_name='uuid', new_name='id'),
    ]
