# Generated by Django 3.1.5 on 2021-02-10 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_auto_20201201_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='added_by',
            field=models.ForeignKey(editable=False,
                                    null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='added_by',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_add_user',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
