# Generated by Django 3.2.3 on 2021-06-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='timer_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timer_pause',
        ),
    ]
