# Generated by Django 3.2.3 on 2021-08-18 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0013_auto_20210726_1729'),
        ('core', '0013_userprofile_email_verified'),
    ]

    operations = []
