# Generated by Django 3.2.13 on 2022-05-28 22:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20210818_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseAuthorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Model ID')),
                ('model_type', models.CharField(choices=[('1', 'Exercise')], editable=False, max_length=3)),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time')),
            ],
            options={
                'ordering': ['model_id', 'model_type', 'name', 'datetime'],
            },
        ),
    ]
