# Generated by Django 3.2.16 on 2022-11-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_merge_20210818_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='short_name',
            field=models.CharField(max_length=2, unique=True, verbose_name='Language short name'),
        ),
    ]
