# Generated by Django 4.2.6 on 2024-01-17 15:41

from django.db import migrations, models


def update_language_full_name(apps, schema_editor):
    mapper = {
        'de': 'German',
        'en': 'English',
        'bg': 'Bulgarian',
        'es': 'Spanish',
        'ru': 'Russian',
        'nl': 'Dutch',
        'pt': 'Portuguese',
        'el': 'Greek',
        'cs': 'Czech',
        'sv': 'Swedish',
        'no': 'Norwegian',
        'fr': 'French',
        'it': 'Italian',
        'pl': 'Polish',
        'uk': 'Ukrainian',
        'tr': 'Turkish',
        'ar': 'Arabic',
        'az': 'Azerbaijani',
        'eo': 'Esperanto',
        'fa': 'Persian',
        'he': 'Hebrew',
        'hr': 'Croatian',
        'id': 'Indonesian',
        'zh': 'Chinese',
    }

    Language = apps.get_model('core', 'Language')
    for language in Language.objects.all():
        language.full_name_en = mapper.get(language.short_name, 'English')
        language.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_alter_language_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='full_name_en',
            field=models.CharField(
                default='english',
                max_length=30,
                verbose_name='Language full name in English',
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            update_language_full_name,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
