# Generated by Django 4.2.6 on 2024-01-17 15:41

from django.db import migrations, models


def update_language_full_name(apps, schema_editor):
    mapper = {1: 'German', 2: 'English', 3: 'Bulgarian', 4: 'Spanish', 5: 'Russian', 6: 'Dutch',
              7: 'Portuguese', 8: 'Greek', 9: 'Czech', 10: 'Swedish', 11: 'Norwegian', 12: 'French',
              13: 'Italian', 14: 'Polish', 15: 'Ukrainian', 16: 'Turkish', 17: 'Arabic',
              18: 'Azerbaijani', 19: 'Esperanto', 20: 'Persian', 21: 'Hebrew', 22: 'Croatian',
              23: 'Indonesian', 24: 'Chinese', }

    Language = apps.get_model("core", "Language")
    for language in Language.objects.all():
        language.full_name_en = mapper.get(language.id, 'English')
        language.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_alter_language_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='full_name_en',
            field=models.CharField(default='english', max_length=30,
                                   verbose_name='Language full name in English', ),
            preserve_default=False,
        ),
        migrations.RunPython(
            update_language_full_name,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
