# Generated by Django 4.2.13 on 2024-09-19 13:43

from django.db import migrations

from wger.utils.db import postgres_only


@postgres_only
def add_publication(apps, schema_editor):
    # Note that "FOR ALL TABLES" applies for all tables created in the future as well
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_publication WHERE pubname = 'powersync'
            ) THEN
                CREATE PUBLICATION powersync FOR ALL TABLES;
            END IF;
        END $$;
        """
    )


@postgres_only
def remove_publication(apps, schema_editor):
    schema_editor.execute('DROP PUBLICATION IF EXISTS powersync;')


@postgres_only
def add_ivm_extension(apps, schema_editor):
    schema_editor.execute('CREATE EXTENSION IF NOT EXISTS pg_ivm;')


@postgres_only
def remove_ivm_extension(apps, schema_editor):
    schema_editor.execute('DROP EXTENSION IF EXISTS pg_ivm;')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0017_language_full_name_en'),
    ]

    operations = [
        migrations.RunPython(add_publication, reverse_code=remove_publication),
        migrations.RunPython(add_ivm_extension, reverse_code=remove_ivm_extension),
    ]
