# Generated by Django 4.2.16 on 2024-12-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0017_language_full_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='repetitions_rounding',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_rounding',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
