# Generated by Django 4.2.16 on 2025-03-15 12:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0021_flexible_routines_cleanup'),
        ('core', '0018_rounding'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DaysOfWeek',
        ),
    ]
