# Generated by Django 5.2.9 on 2025-12-07 18:34

from django.db import migrations, models


def set_unit_types(apps, schema_editor):
    """
    Set the unit_type for existing RepetitionUnit records based on their ID.

    Default units (from fixture):
    - ID 1: Repetitions -> REPETITIONS
    - ID 2: Until Failure -> REPETITIONS
    - ID 3: Seconds -> TIME
    - ID 4: Minutes -> TIME
    - ID 5: Miles -> DISTANCE
    - ID 6: Kilometers -> DISTANCE
    - ID 7: Max Reps -> REPETITIONS
    """
    RepetitionUnit = apps.get_model('core', 'RepetitionUnit')

    # Time-based units
    RepetitionUnit.objects.filter(id__in=[3, 4]).update(unit_type='TIME')

    # Distance-based units
    RepetitionUnit.objects.filter(id__in=[5, 6]).update(unit_type='DISTANCE')

    # Repetition-based units (already default, but explicit for clarity)
    RepetitionUnit.objects.filter(id__in=[1, 2, 7]).update(unit_type='REPETITIONS')


def reverse_unit_types(apps, schema_editor):
    """Reverse migration - no action needed since field will be removed"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_daysofweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetitionunit',
            name='unit_type',
            field=models.CharField(
                choices=[
                    ('REPETITIONS', 'Repetitions'),
                    ('TIME', 'Time'),
                    ('DISTANCE', 'Distance'),
                ],
                default='REPETITIONS',
                help_text='The type of unit (repetitions, time, or distance)',
                max_length=20,
                verbose_name='Unit Type',
            ),
        ),
        migrations.RunPython(set_unit_types, reverse_unit_types),
    ]
