# Generated by Django 5.2.9 on 2025-12-07 18:34

from django.db import migrations, models


def set_unit_types(apps, schema_editor):
    """
    Set the unit_type for existing RepetitionUnit records based on their ID.

    Default units (from fixture):
    - ID 1: Repetitions -> REPETITIONS
    - ID 2: Until Failure -> REPETITIONS
    - ID 3: Seconds -> TIME
    - ID 4: Minutes -> TIME
    - ID 5: Miles -> DISTANCE
    - ID 6: Kilometers -> DISTANCE
    - ID 7: Max Reps -> REPETITIONS
    """
    RepetitionUnit = apps.get_model('core', 'RepetitionUnit')

    # Time-based units
    RepetitionUnit.objects.filter(id__in=[3, 4]).update(unit_type='TIME')
    RepetitionUnit.objects.filter(id=3).update(multiplier=1)  # Seconds -> base unit for time
    RepetitionUnit.objects.filter(id=4).update(multiplier=60)  # Minutes -> 60 seconds

    # Distance-based units
    RepetitionUnit.objects.filter(id__in=[5, 6, 8]).update(unit_type='DISTANCE')
    RepetitionUnit.objects.filter(id=8).update(multiplier=1)  # Meters -> base unit for distance
    RepetitionUnit.objects.filter(id=6).update(multiplier=1000)  # Kilometers -> 1000 meters
    RepetitionUnit.objects.filter(id=5).update(multiplier=1609)  # Miles -> 1609 meters

    # Repetition-based units (already default, but explicit for clarity)
    RepetitionUnit.objects.filter(id__in=[1, 2, 7]).update(unit_type='REPETITIONS')
    RepetitionUnit.objects.filter(id=1).update(multiplier=1)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0020_add_trophies_enabled_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='repetitionunit',
            name='unit_type',
            field=models.CharField(
                choices=[
                    ('REPETITIONS', 'Repetitions'),
                    ('TIME', 'Time'),
                    ('DISTANCE', 'Distance'),
                ],
                default='REPETITIONS',
                help_text='The type of unit (repetitions, time, or distance)',
                max_length=20,
                verbose_name='Unit Type',
            ),
        ),
        migrations.AddField(
            model_name='repetitionunit',
            name='multiplier',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Multiplier to convert this unit to a base unit. Time units are converted\n        to seconds, distance units to meters, and repetitions remain unchanged. For example:\n        minutes -> 60, kilometers -> 1000. Leave empty if a multiplier does not apply.',
                null=True,
                verbose_name='Multiplier',
            ),
        ),
        migrations.AlterModelOptions(
            name='repetitionunit',
            options={'ordering': ['unit_type', 'name']},
        ),
        migrations.RunPython(set_unit_types, reverse_code=migrations.RunPython.noop),
    ]
