# Generated by Django 4.2.13 on 2024-09-19 13:43

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from wger.utils.db import postgres_only


@postgres_only
def add_publication(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    # Note that "FOR ALL TABLES" applies for all tables created in the future as well
    schema_editor.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_publication WHERE pubname = 'powersync'
            ) THEN
                CREATE PUBLICATION powersync FOR ALL TABLES;
            END IF;
        END $$;
        """
    )


@postgres_only
def remove_publication(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    schema_editor.execute('DROP PUBLICATION IF EXISTS powersync;')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_move_email_verified_to_emailaddress'),
    ]

    operations = [
        migrations.RunPython(add_publication, reverse_code=remove_publication),
    ]
