# Generated by Django 4.2.13 on 2024-09-19 13:43

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

from wger.utils.db import postgres_only


def add_publication(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    # This used to create the publication "FOR ALL TABLES", which requires a database
    # superuser and made the migration fail on managed databases. It is now created
    # with an explicit list of tables, see migration 0027.
    pass


@postgres_only
def remove_publication(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    schema_editor.execute('DROP PUBLICATION IF EXISTS powersync;')


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_move_email_verified_to_emailaddress'),
    ]

    operations = [
        migrations.RunPython(add_publication, reverse_code=remove_publication),
    ]
