# Generated by Django 6.0.5 on 2026-06-15 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0024_backfill_emailaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ro_access',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_comments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='show_english_ingredients',
        ),
    ]
