# Generated by Django 6.0.5 on 2026-06-15 13:42

import django.core.validators
import wger.core.models.profile
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0025_remove_unused_fields_in_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(
                blank=True,
                null=True,
                validators=[wger.core.models.profile.birthdate_validator],
                verbose_name='Date of Birth',
            ),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(140),
                    django.core.validators.MaxValueValidator(230),
                ],
                verbose_name='Height (cm)',
            ),
        ),
    ]
