# Generated by Django 5.2.6 on 2025-09-28 19:58
from _datetime import datetime
import uuid
from django.db import migrations, models
from django.utils import timezone


def copy_date_to_created(apps, schema_editor):
    Measurement = apps.get_model('measurements', 'Measurement')
    for obj in Measurement.objects.all():
        obj.created = obj.date
        obj.save(update_fields=['created'])


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0002_auto_20210722_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set(),
        ),


        migrations.AlterField(
            model_name='measurement',
            name='date',
            field=models.DateTimeField(default=timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='category',
            name='internal_name',
            field=models.CharField(
                max_length=100,
                blank=True,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='externally_synced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='measurement',
            name='external_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='source',
            field=models.CharField(
                default='manual',
                max_length=100,
                verbose_name='Source',
            ),
        ),
        migrations.AddField(
            model_name='measurement',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='measurement',
            name='created',
            field=models.DateTimeField(default=timezone.now, verbose_name='Date'),
        ),
        migrations.RunPython(copy_date_to_created, reverse_code=migrations.RunPython.noop),
    ]
