# Generated by Django 5.2.12 on 2026-03-13 14:05

import uuid
from django.db import migrations, models
from django.db.migrations.state import StateApps


def gen_uuids(apps: StateApps, schema_editor):
    Category = apps.get_model('measurements', 'Category')
    Measurement = apps.get_model('measurements', 'Measurement')

    for item in Category.objects.all():
        item.uuid = uuid.uuid4()
        item.save(update_fields=['uuid'])

    for item in Measurement.objects.all():
        item.uuid = uuid.uuid4()
        item.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0003_alter_measurement_unique_together_and_more'),
    ]

    operations = [
        # Don't force uniqueness
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=False,
            ),
        ),
        migrations.AddField(
            model_name='measurement',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=False,
            ),
        ),
        # Generate the UUIDs
        migrations.RunPython(
            gen_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        # Close everything back up
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=False,
                unique=True,
            ),
        ),
    ]
