# Generated by Django 5.2.12 on 2026-03-13 14:05
"""
Convert Category and Measurement to use UUID primary keys.

Pattern matches the four-step transition we use for nutrition:

1. Add `uuid` columns to both tables and backfill them.
2. Repoint Measurement.category through a temporary `category_tmp` UUID column
   copied from the parent's uuid.
3. Promote each table's `uuid` to the primary key (drop the integer `id`,
   rename `uuid` -> `id`).
4. Restore Measurement.category as a ForeignKey to the new UUID PK.
"""

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations.state import StateApps
from django.db.models import OuterRef, Subquery

from wger.utils.uuid import uuid7


def gen_uuids(apps: StateApps, schema_editor):
    Category = apps.get_model('measurements', 'Category')
    Measurement = apps.get_model('measurements', 'Measurement')

    for item in Category.objects.all():
        item.uuid = uuid7()
        item.save(update_fields=['uuid'])

    for item in Measurement.objects.all():
        item.uuid = uuid7()
        item.save(update_fields=['uuid'])


def populate_measurement_category_tmp(apps: StateApps, schema_editor):
    Measurement = apps.get_model('measurements', 'Measurement')
    Category = apps.get_model('measurements', 'Category')
    Measurement.objects.update(
        category_tmp=Subquery(
            Category.objects.filter(id=OuterRef('category')).values('uuid')[:1],
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0003_alter_measurement_unique_together_and_more'),
    ]

    operations = [
        # ------------------------------------------------------------------
        # 1. Add uuid columns and backfill
        # ------------------------------------------------------------------
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=True, unique=False),
        ),
        migrations.AddField(
            model_name='measurement',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=True, unique=False),
        ),
        migrations.RunPython(gen_uuids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=False, unique=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='uuid',
            field=models.UUIDField(default=uuid7, null=False, unique=True),
        ),
        # ------------------------------------------------------------------
        # 2. Repoint Measurement.category through tmp uuid column
        # ------------------------------------------------------------------
        migrations.AddField(
            model_name='measurement',
            name='category_tmp',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_measurement_category_tmp, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(model_name='measurement', name='category'),
        # ------------------------------------------------------------------
        # 3. Promote uuid -> primary key
        # ------------------------------------------------------------------
        migrations.RemoveField(model_name='category', name='id'),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(
                default=uuid7,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.RemoveField(model_name='measurement', name='id'),
        migrations.AlterField(
            model_name='measurement',
            name='uuid',
            field=models.UUIDField(
                default=uuid7,
                primary_key=True,
                serialize=False,
            ),
        ),
        # ------------------------------------------------------------------
        # 4. Restore Measurement.category FK to the new UUID PK
        # ------------------------------------------------------------------
        migrations.RenameField(
            model_name='measurement',
            old_name='category_tmp',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='measurements.category',
                verbose_name='Category',
            ),
        ),
        # ------------------------------------------------------------------
        # 5. Rename uuid -> id on both tables
        # ------------------------------------------------------------------
        migrations.RenameField(model_name='category', old_name='uuid', new_name='id'),
        migrations.RenameField(model_name='measurement', old_name='uuid', new_name='id'),
    ]
