# Generated by Django 5.2.14 on 2026-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0003_alter_measurement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dynamic_params',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Configuration parameters for dynamic calculations',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='dynamic_type',
            field=models.CharField(
                choices=[('NONE', 'None'), ('BMI', 'Bmi')],
                db_index=True,
                default='NONE',
                max_length=20,
            ),
        ),
    ]
