# Generated by Django 5.2.14 on 2026-05-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0003_alter_measurement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_dynamic',
            field=models.BooleanField(
                default=False,
                help_text='Indicates if this category is automatically calculated.',
                verbose_name='Is Dynamic',
            ),
        ),
    ]
