# Generated by Django 5.2.12 on 2026-03-15 11:29

"""
This migration replaces the integer Primary Key of the Category model with a UUID.

Since this is not directly possible, the following steps are taken:

1. Add a temporary UUID field (`category_tmp`) to Measurement and populate it with
   existing related category UUIDs.
2. Remove the old integer `category` ForeignKey.
3. Switch the Category model's Primary Key from `id` to `uuid`.
4. Restore `Measurement.category` as a ForeignKey (pointing to the new UUID PK).
5. Rename `Category.uuid` to `id` (while keeping the UUID type).
"""

from wger.utils.uuid import uuid7
from django.db import migrations, models
from django.db.migrations.state import StateApps
from django.db.models import Subquery, OuterRef


def populate_category_tmp(apps: StateApps, schema_editor):
    Measurement = apps.get_model('measurements', 'Measurement')
    Category = apps.get_model('measurements', 'Category')

    Measurement.objects.update(
        category_tmp=Subquery(
            Category.objects.filter(id=OuterRef('category')).values('uuid')[:1],
        )
    )


def reverse_populate_category_tmp(apps: StateApps, schema_editor):
    Measurement = apps.get_model('measurements', 'Measurement')
    for m in Measurement.objects.all():
        m.category_tmp = None
        m.save(update_fields=['category_tmp'])


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0003_add_uuids'),
    ]

    operations = [
        # Add tmp UUID field and copy the category UUIDs into it.
        migrations.AddField(
            model_name='measurement',
            name='category_tmp',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(populate_category_tmp, reverse_populate_category_tmp),
        # Remove old FK
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='category',
        ),
        # Change category PK
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(
                default=uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        # Rename "category_tmp" back to "category"
        migrations.RenameField(
            model_name='measurement',
            old_name='category_tmp',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('date', 'category')},
        ),
        # Make category
        migrations.AlterField(
            model_name='measurement',
            name='category',
            field=models.UUIDField(db_column='category_id', editable=False, null=True),
        ),
        # Change the FK and rename
        migrations.AlterField(
            model_name='measurement',
            name='category',
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                to='measurements.category',
                verbose_name='Category',
            ),
        ),
        migrations.RenameField(
            model_name='category',
            old_name='uuid',
            new_name='id',
        ),
    ]
