# Generated by Django 5.2.14 on 2026-05-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0004_category_is_dynamic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_dynamic',
        ),
        migrations.AddField(
            model_name='category',
            name='dynamic_type',
            field=models.CharField(choices=[('NONE', 'None'), ('BMI', 'Bmi'), ('SQUAT_1RM', 'Squat 1Rm')], db_index=True, default='NONE', max_length=20),
        ),
    ]
