# Generated by Django 6.0.5 on 2026-07-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0005_alter_measurement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='externally_synced',
            field=models.BooleanField(default=False, verbose_name='Externally synced'),
        ),
        migrations.AddField(
            model_name='category',
            name='metric_type',
            field=models.CharField(
                choices=[
                    ('custom', 'Custom'),
                    ('body_weight', 'Body Weight'),
                    ('body_fat', 'Body Fat'),
                    ('height', 'Height'),
                    ('blood_pressure', 'Blood Pressure'),
                    ('heart_rate', 'Heart Rate'),
                    ('steps', 'Steps'),
                    ('distance', 'Distance'),
                    ('energy', 'Energy'),
                    ('sleep', 'Sleep'),
                ],
                default='custom',
                max_length=20,
                verbose_name='Metric type',
            ),
        ),
        migrations.AddField(
            model_name='measurement',
            name='external_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='source',
            field=models.CharField(
                choices=[('user', 'User'), ('google', 'Google'), ('apple', 'Apple')],
                default='user',
                max_length=10,
                verbose_name='Source',
            ),
        ),
    ]
