# Generated by Django 5.2.12 on 2026-03-15 12:21

from django.db import migrations, models
from wger.utils.uuid import uuid7


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0005_change_category_pk_type_to_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='id',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.UUIDField(
                default=uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
