# Generated by Django 6.0.5 on 2026-07-01 14:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0005_alter_measurement_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='unit',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='children',
                to='measurements.category',
                verbose_name='Parent',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='metric_type',
            field=models.CharField(
                choices=[
                    ('custom', 'Custom'),
                    ('body_weight', 'Body Weight'),
                    ('body_fat', 'Body Fat'),
                    ('lean_body_mass', 'Lean Body Mass'),
                    ('height', 'Height'),
                    ('blood_pressure', 'Blood Pressure'),
                    ('blood_pressure_systolic', 'Blood Pressure Systolic'),
                    ('blood_pressure_diastolic', 'Blood Pressure Diastolic'),
                    ('heart_rate', 'Heart Rate'),
                    ('resting_heart_rate', 'Resting Heart Rate'),
                    ('blood_oxygen', 'Blood Oxygen'),
                    ('steps', 'Steps'),
                    ('distance', 'Distance'),
                    ('energy', 'Energy'),
                    ('sleep', 'Sleep'),
                    ('sleep_total', 'Total sleep'),
                    ('sleep_light', 'Light sleep'),
                    ('sleep_deep', 'Deep sleep'),
                    ('sleep_rem', 'REM sleep'),
                    ('sleep_awake', 'Awake'),
                ],
                default='custom',
                max_length=30,
                verbose_name='Metric type',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='chart_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('line', 'Line'),
                    ('bar', 'Bar'),
                    ('heatmap', 'Heatmap'),
                    ('delta', 'Delta'),
                    ('distribution', 'Distribution'),
                ],
                max_length=20,
                null=True,
                verbose_name='Chart type',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Chart config'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(
                condition=models.Q(('metric_type', 'custom'), _negated=True),
                fields=('user', 'metric_type'),
                name='unique_typed_category_per_user',
            ),
        ),
        migrations.AddField(
            model_name='measurement',
            name='external_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='External ID'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='source',
            field=models.CharField(
                choices=[('user', 'User'), ('google', 'Google'), ('apple', 'Apple')],
                default='user',
                max_length=10,
                verbose_name='Source',
            ),
        ),
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(
                condition=models.Q(('external_id__isnull', False)),
                fields=('category', 'source', 'external_id'),
                name='unique_external_measurement',
            ),
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(
                fields=['category', '-date', '-id'],
                name='measurement_category_date',
            ),
        ),
        # Daily step and energy totals do not fit into the old numeric(6, 2),
        # and the flat 5000 cap was the binding limit no matter what a metric
        # type allows. The bounds per metric type live in
        # wger.measurements.limits and are checked in the serializer instead.
        # The column only gets wider, so no existing row can violate it; on
        # Postgres the precision change rewrites the table
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='Value',
            ),
        ),
        # Powersync only re-replicates existing rows when the sync rules file changes
        # or when the data changes. In order to avoid problems for self-hoster that
        # have not updated the docker repo, we do a no-op update, that forces a
        # re-sync of the buckets
        migrations.RunSQL(
            sql=[
                'UPDATE measurements_category SET id = id;',
                'UPDATE measurements_measurement SET id = id;',
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
