# Generated by Django 5.2.14 on 2026-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0007_migrate_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dynamic_params',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Configuration parameters for dynamic calculations',
            ),
        ),
        migrations.AddField(
            model_name='category',
            name='dynamic_type',
            field=models.CharField(
                choices=[
                    ('NONE', 'None'),
                    ('BMI', 'BMI'),
                    ('WHTR', 'Waist-to-height ratio'),
                    ('ONE_REP_MAX', '1RM'),
                ],
                db_index=True,
                default='NONE',
                max_length=20,
            ),
        ),
    ]
