# Generated by Django 6.0.8 on 2026-08-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('measurements', '0008_dynamic_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='source',
            field=models.CharField(
                choices=[
                    ('user', 'User'),
                    ('google', 'Google'),
                    ('apple', 'Apple'),
                    ('calculated', 'Calculated'),
                ],
                default='user',
                max_length=10,
                verbose_name='Source',
            ),
        ),
    ]
