# Generated by Django 3.1 on 2020-08-30 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('manager', '0008_auto_20190618_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='group',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
    ]
