# Generated by Django 3.1.2 on 2020-11-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20190618_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='rpe',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, null=True, verbose_name='rpe'),
        ),
    ]
