# Generated by Django 3.1.3 on 2021-01-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20201202_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='rir',
            field=models.CharField(blank=True,
                                   choices=[(None, '------'), ('0', 0), ('0.5', 0.5), ('1', 1),
                                            ('1.5', 1.5), ('2', 2), ('2.5', 2.5), ('3', 3),
                                            ('3.5', 3.5), ('4', 4)],
                                   max_length=3, null=True, verbose_name='RiR'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='rir',
            field=models.CharField(blank=True,
                                   choices=[(None, '------'), ('0', 0), ('0.5', 0.5), ('1', 1),
                                            ('1.5', 1.5), ('2', 2), ('2.5', 2.5), ('3', 3),
                                            ('3.5', 3.5), ('4', 4)],
                                   max_length=3, null=True, verbose_name='RiR'),
        ),
    ]
