# Generated by Django 3.1.3 on 2020-11-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20201111_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='rpe',
            field=models.DecimalField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5),
                                                           (6, 6), (7, 7), (7.5, 7.5), (8, 8),
                                                           (8.5, 8.5), (9, 9), (9.5, 9.5),
                                                           (10, 10)], decimal_places=1, default=5,
                                      max_digits=3, null=True, verbose_name='rpe'),
        ),
    ]
