# Generated by Django 3.1.8 on 2021-04-30 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0011_remove_set_exercises'),
    ]

    operations = [
        migrations.RenameField(model_name='workout', old_name='comment', new_name='name'),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(
                blank=True,
                help_text='A short description or goal of the workout. For '
                "example 'Focus on back' or 'Week 1 of program xy'.",
                max_length=1000,
                verbose_name='Description',
            ),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(
                blank=True, help_text='The name of the workout', max_length=100, verbose_name='Name'
            ),
        ),
        migrations.AlterField(
            model_name='setting',
            name='reps',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(600),
                ],
                verbose_name='Reps',
            ),
        ),
    ]
