# Generated by Django 3.2.3 on 2021-10-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0014_auto_20210717_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='is_public',
            field=models.BooleanField(
                default=False,
                help_text='A public template is available to other users',
                verbose_name='Public template',
            ),
        ),
        migrations.AlterField(
            model_name='workout',
            name='is_template',
            field=models.BooleanField(
                default=False,
                help_text='Marking a workout as a template will freeze it and allow you to make copies of it',
                verbose_name='Workout template',
            ),
        ),
    ]
