# Generated by Django 3.2.10 on 2022-04-20 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0020_auto_20220302_2136'),
        ('manager', '0015_auto_20211028_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutlog',
            old_name='exercise',
            new_name='exercise_base',
        ),
    ]
