# Generated by Django 3.2.13 on 2022-05-28 22:29

from django.db import migrations, models
import django.db.models.deletion

# Mapping of bases that should be migrated
# -> (old_base, new_base)
base_mapping = [
    (
        '201edd07-93f8-474b-8db0-e13e5283ee2b',
        '1b9ed9da-46d1-4484-8acc-236379ee823c',
    ),  # Kabelziehen Über Kreuz
    ('b7b690a7-2e65-40f9-a9cb-e61501a72fed', 'b16e3e5d-8401-4d2b-919c-15b536f9ec5e'),  # Kabelzug
    ('713ee452-2775-4a68-8a7c-f1d22b5cd469', '00fcf603-b0d0-48d2-9b5e-c7f0d510d46c'),  # Rudern eng
    (
        '4ceb1ba5-1ce1-4fe3-b60a-5d0e173a2ab3',
        '61950a59-be4e-43cc-abc1-cb52abd15354',
    ),  # Leg extension
    (
        '27d322ba-cbf5-44fa-a3bc-1999c6711757',
        '058945bb-7fa8-4724-95fb-51ee8df20929',
    ),  # Beinstrecker
    (
        '557ae429-100d-4d5b-a173-e5186fa2d9bc',
        '13234b53-ea0c-41f1-9069-776865ea8eff',
    ),  # Trizepsdrücken KH Über Kopf
    (
        '455fc17f-dc4c-4516-a335-8286958e7a7b',
        '09dd3e3c-e53a-4e2c-a2e3-645d334f53e2',
    ),  # Triceps Dips
    (
        'a1d4f524-b6ca-4dd3-9998-41200f01b634',
        '3db63138-a047-4a4d-b616-1a0b7dfca105',
    ),  # Close-grip Bench Press
    (
        '69378ddf-377d-4624-b500-3406682a84e4',
        '275fb49f-975c-4d6e-9d63-2c86ed740f40',
    ),  # Incline Bench Press
    (
        '64d772ea-f21a-47c1-8660-d6b9366d1900',
        '57e17672-52b9-43cf-8d0d-4b3f06a0c0d0',
    ),  # Incline Bench Press - Dumbbell
    ('6a496c73-721d-4ed2-9f7f-337e8ad2b388', '09dd3e3c-e53a-4e2c-a2e3-645d334f53e2'),  # Dips
    (
        '133f7a01-dd9f-45d5-af67-1d1af134d99b',
        '4af6dbd9-8991-484b-9810-68f117c21edf',
    ),  # Bent Over Barbell Row
    (
        '8f7b6fce-4a75-42fc-b217-efe44e349fdc',
        '94a5c406-7bcd-47f3-9687-bdf92a763932',
    ),  # Einarmiges Rudern KH
    ('7a69e726-cdb2-4f0a-b9bd-a9c560d04a03', '7ce443b6-eb84-4f65-b05f-461c1cc8bcc0'),  # Calf raises
    (
        'c323d8a4-310f-4381-925c-3893ef5f8422',
        '63fbb8e5-6ebc-4def-8844-3e65e097213b',
    ),  # Latzug Eng im Untergriff Zur Brust
    (
        'c29884c8-a4fd-4491-8bfd-2dac88aa7184',
        '34fc154f-cc8d-4e52-adb7-ff0dad2d0770',
    ),  # Latzug Breit Zur Brust
    (
        '9e694c44-2462-430d-8108-6982fd681ade',
        '63fbb8e5-6ebc-4def-8844-3e65e097213b',
    ),  # Lat Pulldown
    ('2d806ebb-9aa3-449b-9056-218f5bbbc7f8', 'a2f5b6ef-b780-49c0-8d96-fdaff23e27ce'),  # Squat
    ('a2f5b6ef-b780-49c0-8d96-fdaff23e27ce', 'a2f5b6ef-b780-49c0-8d96-fdaff23e27ce'),  # Squat
    (
        '5912d7ed-6a0e-4b4c-b30a-fc9f3f890fc1',
        '5912d7ed-6a0e-4b4c-b30a-fc9f3f890fc1',
    ),  # Shoulder Press, on Machine
    ('9b210eb3-6ff0-4a57-8e26-e89da8751c19', '63375f5b-2d81-471c-bea4-fc3d207e96cb'),  # Side Raise
    ('39ba20a7-14c7-44fe-b6c8-6ce9c83b4c38', '52dec48d-25a4-4a78-b66b-ad6a773e143a'),  # Power Clean
    (
        '058945bb-7fa8-4724-95fb-51ee8df20929',
        '058945bb-7fa8-4724-95fb-51ee8df20929',
    ),  # Leg Extension
    (
        '49859097-644a-417a-8cb7-491b7d8bc383',
        '53906cd1-61f1-4d56-ac60-e4fcc5824861',
    ),  # Adduktoren Maschine
    (
        'b955b629-5c57-4f98-b200-e96e138c300f',
        '5f514f9e-6bd9-408e-85b2-c25eb04af33b',
    ),  # Beinheben Aufrecht
    (
        '5f8370d9-aa89-4dcc-9d97-d9da86a2f183',
        '9b993e99-8701-43f0-84d6-689123183880',
    ),  # Beinheben im Hang
    (
        '5b14e0f0-1131-4ad9-9821-5703f1370bc5',
        '9e34bc01-9cec-4ee2-a9bb-9c937a471c24',
    ),  # Beinheben Liegend
    (
        'e878ecf3-fbb2-4f0e-a546-9769c7ff3241',
        '2e7ffff9-e603-4b28-98c8-31d1a6ce8cd9',
    ),  # Rumänisches Kreuzheben
    (
        '24b62fb4-0158-486e-89f1-9a5f1db234ef',
        '32c129f7-cc28-4ebc-8465-e4fa62e220b1',
    ),  # T-Bar Rudern (breit)
    (
        '515cb39c-fead-4b59-a4ba-a10c5b0b8c84',
        '9c35594c-bbcc-4656-bdcb-376814c90e96',
    ),  # Frontheben am Kabel
    (
        'cfeedd4f-84e3-402c-a105-ec985658c927',
        '591992cb-48ee-4b39-b790-e05b4a2c11e3',
    ),  # Weighted Step
    (
        '6c86a314-bf0e-4b31-aea7-40891fa5288a',
        '2f7149c3-77ce-4313-a59c-aef82b5a730a',
    ),  # Lat-Ziehen Mit Gesteckten Armen am Seilzug
    (
        '09ed42ad-5523-424d-bd64-c439694a65fe',
        '63375f5b-2d81-471c-bea4-fc3d207e96cb',
    ),  # Shoulder Fly
    (
        '73405d63-a539-486e-996e-1e72572fbe5d',
        '6e00afb6-272d-44a2-8ae3-e7fa41b50f06',
    ),  # Pull-Over KH
    (
        '9ae8772d-570c-4d16-abd4-34f5d5081e4e',
        '6f79b381-98a4-40d5-8a45-3bb0558be6fe',
    ),  # Seitheben Kurzhantel Vorgebeugt
    (
        '31f51ab6-94a6-436f-9d41-632d85b7e01f',
        '141bc870-56be-4749-a3b9-e56d5d5618b4',
    ),  # Frontdrücken MP
    (
        'a68c991c-ac42-47c8-9a84-9b288a4a7a76',
        '5d40c67d-be59-4092-9c9c-301ca5310e2b',
    ),  # Rudern Aufrecht ß-Stange
]


def migrate_bases(apps, schema_editor):
    """
    Migrates the used bases

    Note that we can't access STATUS_PENDING here because we are not using
    a real model.
    """
    WorkoutLog = apps.get_model('manager', 'WorkoutLog')
    Setting = apps.get_model('manager', 'Setting')
    Base = apps.get_model('exercises', 'ExerciseBase')
    for mapping in base_mapping:
        try:
            base_old = Base.objects.get(uuid=mapping[0])
            base_new = Base.objects.get(uuid=mapping[1])
        except Base.DoesNotExist:
            # print(f'Could not load base {base_old} or {base_new}')
            continue

        WorkoutLog.objects.filter(exercise_base=base_old).update(exercise_base=base_new)
        Setting.objects.filter(exercise_base=base_old).update(exercise_base=base_new)


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0019_exercise_crowdsourcing_changes'),
        ('manager', '0016_move_to_exercise_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='exercise_base',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='exercises.exercisebase',
                verbose_name='Exercise',
            ),
        ),
        migrations.RunPython(migrate_bases),
    ]
