# Generated by Django 3.2.13 on 2022-05-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_exercise_crowdsourcing_changes'),
        ('manager', '0016_move_to_exercise_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='exercise_base',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='exercises.exercisebase',
                verbose_name='Exercise'
            ),
        ),
    ]
