# Generated by Django 4.2.6 on 2024-04-20 04:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0018_setting_moved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='moved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1500)], verbose_name='Weight-Moved'),
            preserve_default=False,
        ),
    ]
