# Generated by Django 4.2.6 on 2024-03-07 19:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0028_add_uuid_alias_and_comments'),
        ('core', '0016_alter_language_short_name'),
        ('manager', '0018_flexible_routines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repsconfig',
            options={'ordering': ['set_config', 'iteration']},
        ),
        migrations.AlterModelOptions(
            name='restconfig',
            options={'ordering': ['set_config', 'iteration']},
        ),
        migrations.AlterModelOptions(
            name='rirconfig',
            options={'ordering': ['set_config', 'iteration']},
        ),
        migrations.AlterModelOptions(
            name='weightconfig',
            options={'ordering': ['set_config', 'iteration']},
        ),
        migrations.AddField(
            model_name='repsconfig',
            name='need_log_to_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restconfig',
            name='need_log_to_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rirconfig',
            name='need_log_to_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weightconfig',
            name='need_log_to_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='session',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='manager.workoutsession',
                verbose_name='Session',
            ),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='set_config',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.setconfig'
            ),
        ),
        migrations.AlterField(
            model_name='setconfig',
            name='exercise',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='exercises.exercisebase'
            ),
        ),
        migrations.AlterField(
            model_name='setconfig',
            name='repetition_unit',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='core.repetitionunit'
            ),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterUniqueTogether(
            name='repsconfig',
            unique_together={('set_config', 'iteration')},
        ),
        migrations.AlterUniqueTogether(
            name='restconfig',
            unique_together={('set_config', 'iteration')},
        ),
        migrations.AlterUniqueTogether(
            name='rirconfig',
            unique_together={('set_config', 'iteration')},
        ),
        migrations.AlterUniqueTogether(
            name='weightconfig',
            unique_together={('set_config', 'iteration')},
        ),
        migrations.RemoveField(
            model_name='repsconfig',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='restconfig',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='rirconfig',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='weightconfig',
            name='creation_date',
        ),
    ]
