# Generated by Django 4.2.6 on 2024-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0019_alter_repsconfig_options_alter_restconfig_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='iteration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='setconfig',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='setconfig',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
