# Generated by Django 4.2.6 on 2024-04-20 05:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0020_alter_setting_moved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='moved',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1500)], verbose_name='Weight-Moved'),
        ),
    ]
