# Generated by Django 4.2.6 on 2024-03-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0020_workoutlog_iteration_alter_setconfig_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setconfig',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
