# Generated by Django 4.2.16 on 2025-02-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0021_flexible_routines_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotentry',
            name='has_progression',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
