# Generated by Django 4.2.20 on 2025-03-25 19:34

from django.db import migrations, models
import wger.manager.validators


def migrate_forward(apps, schema_editor):
    Log = apps.get_model('manager', 'WorkoutLog')

    Log.objects.filter(rir='').update(rir=None)
    Log.objects.filter(rir_target='').update(rir=None)


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0021_flexible_routines_cleanup'),
    ]

    operations = [
        migrations.RunPython(migrate_forward, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='workoutlog',
            name='rir',
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[wger.manager.validators.NullMinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='rir_target',
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[wger.manager.validators.NullMinValueValidator(0)],
            ),
        ),
    ]
