# Generated by Django 5.2.7 on 2025-10-24 14:07

import uuid
from django.db import migrations, models

from wger.utils.db import backfill_uuid_column


def gen_uuids(apps, schema_editor):
    backfill_uuid_column(apps.get_model('manager', 'WorkoutLog'))
    backfill_uuid_column(apps.get_model('manager', 'WorkoutSession'))


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0023_change_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Generate UUIDs
        migrations.RunPython(
            gen_uuids,
            reverse_code=migrations.RunPython.noop,
        ),
        # Set uuid fields to non-nullable
        migrations.AlterField(
            model_name='workoutsession',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=True, null=False),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=True, null=False),
        ),
    ]
