# Generated by Django 5.x
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0023_change_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightconfig',
            name='rir_baseline',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='The weight the user can lift at RiR=0 (i.e. true 1RM or '
                'max effort weight). Used when step=rir_pct to compute the '
                'weekly weight as a percentage of this baseline. '
                'Leave blank to auto-detect from logs (max weight where rir=0).',
                max_digits=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3000),
                ],
            ),
        ),
        migrations.AddField(
            model_name='maxweightconfig',
            name='rir_baseline',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='The max weight the user can lift at RiR=0.',
                max_digits=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3000),
                ],
            ),
        ),
    ]
