# Generated by Django 5.2.7 on 2025-10-02 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            'exercises',
            '0034_rename_exercises_e_name_ac11f4_gin_exercises_t_name_6264c9_gin_and_more',
        ),
        ('manager', '0023_change_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotentry',
            name='custom_exercise',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='slot_entries',
                to='exercises.customexercise',
            ),
        ),
    ]
