# Generated by Django 4.2.6 on 2024-04-20 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0024_alter_setting_moved'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='moved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Weight-Moved'),
        ),
    ]
