# Generated by Django 5.2.12 on 2026-03-15 14:39

from django.db import migrations, models
from django.db.migrations.state import StateApps

from django.db.models import Subquery, OuterRef


def populate_tmp_fields(apps: StateApps, schema_editor):
    WorkoutLog = apps.get_model('manager', 'WorkoutLog')
    WorkoutSession = apps.get_model('manager', 'WorkoutSession')

    # session_tmp
    WorkoutLog.objects.update(
        session_tmp=Subquery(
            WorkoutSession.objects.filter(id=OuterRef('session')).values('uuid')[:1]
        )
    )

    # next_log_tmp
    WorkoutLog.objects.update(
        next_log_tmp=Subquery(
            WorkoutLog.objects.filter(id=OuterRef('next_log')).values('uuid')[:1],
        )
    )


def reverse_populate_tmp_fields(apps: StateApps, schema_editor):
    WorkoutLog = apps.get_model('manager', 'WorkoutLog')
    WorkoutLog.objects.update(session_tmp=None, next_log_tmp=None)


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0024_log_and_session_uuid'),
    ]

    operations = [
        # --- Add tmp fields ---
        migrations.AddField(
            model_name='workoutlog',
            name='session_tmp',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='next_log_tmp',
            field=models.UUIDField(null=True, editable=False),
        ),
        # Populate tmp fields
        #
        # The schema swap that consumes these temporary fields lives in
        # 0026_change_pk_to_uuid_swap. Splitting the data and schema parts
        # so that each runs in its own transaction, otherwise errors might
        # occur.
        migrations.RunPython(populate_tmp_fields, reverse_populate_tmp_fields),
    ]
