# Generated by Django 5.2.12 on 2026-03-15 14:45

import django.db.models.deletion
import wger.manager.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_create_publication'),
        ('manager', '0025_change_pk_to_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotentry',
            name='type',
            field=models.CharField(
                choices=[
                    ('normal', 'Normal'),
                    ('warmup', 'Warmup'),
                    ('dropset', 'Dropset'),
                    ('myo', 'Myo'),
                    ('partial', 'Partial'),
                    ('forced', 'Forced'),
                    ('tut', 'Tut'),
                    ('iso', 'Iso Hold'),
                    ('jump', 'Jump'),
                ],
                default='normal',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='repetitions_target',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[wger.manager.validators.NullMinValueValidator(0)],
                verbose_name='Repetitions target',
            ),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='repetitions_unit',
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.repetitionunit',
                verbose_name='Repetitions unit',
            ),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='weight_target',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                validators=[wger.manager.validators.NullMinValueValidator(0)],
                verbose_name='Weight target',
            ),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='weight_unit',
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.weightunit',
                verbose_name='Weight unit',
            ),
        ),
    ]
