# Generated by Django 5.2.12 on 2026-03-15 14:39

from django.db import migrations, models

from wger.utils.uuid import uuid7


class Migration(migrations.Migration):
    """
    Swap the integer PKs of WorkoutSession and WorkoutLog for the UUIDs that
    0025 populated into temporary fields.

    This migration is intentionally separate from 0025 so that the data
    migration in 0025 commits first.
    """

    dependencies = [
        ('manager', '0025_change_pk_to_uuid'),
    ]

    operations = [
        # --- Remove FKs ---
        migrations.RemoveField(
            model_name='workoutlog',
            name='session',
        ),
        migrations.RemoveField(
            model_name='workoutlog',
            name='next_log',
        ),
        # --- Change PKs ---
        # WorkoutSession
        migrations.RemoveField(
            model_name='workoutsession',
            name='id',
        ),
        migrations.RenameField(
            model_name='workoutsession',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='id',
            field=models.UUIDField(
                default=uuid7, primary_key=True, serialize=False
            ),
        ),
        # WorkoutLog
        migrations.RemoveField(
            model_name='workoutlog',
            name='id',
        ),
        migrations.RenameField(
            model_name='workoutlog',
            old_name='uuid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='id',
            field=models.UUIDField(
                default=uuid7, primary_key=True, serialize=False
            ),
        ),
        # --- Restore FKs ---
        # WorkoutLog.session
        migrations.RenameField(
            model_name='workoutlog',
            old_name='session_tmp',
            new_name='session',
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='session',
            field=models.UUIDField(db_column='session_id', null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='session',
            field=models.ForeignKey(
                to='manager.WorkoutSession',
                verbose_name='Session',
                on_delete=models.CASCADE,
                null=True,
                related_name='logs',
            ),
        ),
        # WorkoutLog.next_log
        migrations.RenameField(
            model_name='workoutlog',
            old_name='next_log_tmp',
            new_name='next_log',
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='next_log',
            field=models.UUIDField(db_column='next_log_id', null=True, editable=False),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='next_log',
            field=models.ForeignKey(
                to='manager.WorkoutLog',
                editable=True,
                on_delete=models.CASCADE,
                null=True,
                default=None,
            ),
        ),
    ]
