# Generated by Django 6.0.6 on 2026-07-28 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0027_cleanup_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
