# Generated by Django 6.0.5 on 2026-07-06 12:51

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def forward_func(apps, schema_editor):
    WorkoutSession = apps.get_model('manager', 'WorkoutSession')
    import datetime
    from django.utils.timezone import make_aware

    for session in WorkoutSession.objects.all():
        start_time = session.time_start if session.time_start else datetime.time(0, 0)
        # Handle cases where date might be None, though default is today, just in case
        date = session.date if session.date else datetime.date.today()
        session.datetime_start = make_aware(datetime.datetime.combine(date, start_time))

        if session.time_end:
            session.datetime_end = make_aware(datetime.datetime.combine(date, session.time_end))
            if session.time_end < start_time:
                session.datetime_end += datetime.timedelta(days=1)
        session.save()


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0027_cleanup_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['datetime_start']},
        ),
        migrations.RemoveIndex(
            model_name='workoutsession',
            name='manager_wor_routine_224494_idx',
        ),
        migrations.AlterUniqueTogether(
            name='workoutsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date and time'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='datetime_start',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Start date and time'
            ),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(
                fields=['routine', 'datetime_start'], name='manager_wor_routine_46e75a_idx'
            ),
        ),
        migrations.RunPython(forward_func),
        migrations.RemoveField(
            model_name='workoutsession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='time_start',
        ),
    ]
