# Generated by Django 6.0.5 on 2026-07-06 12:51

import datetime

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Max, Min, Q
from django.utils.timezone import make_aware


BATCH_SIZE = 2000


def combine(date, time):
    return make_aware(datetime.datetime.combine(date, time))


def build_interval(session):
    """
    Map the old date/time_start/time_end triple onto a start and end datetime
    """
    if session.time_start:
        start = combine(session.date, session.time_start)
        end = None
        if session.time_end:
            end = combine(session.date, session.time_end)
            # An end before the start means the session ran over midnight
            if session.time_end < session.time_start:
                end += datetime.timedelta(days=1)
        return start, end

    # An end without a start was never valid, but nothing enforced it
    if session.time_end:
        return combine(session.date, datetime.time(0, 0)), combine(session.date, session.time_end)

    # No times recorded: the logs know when it actually happened
    if session.first_log:
        last = session.last_log
        return session.first_log, last if last > session.first_log else None

    # Nothing to go by, keep the day and leave the session open
    return combine(session.date, datetime.time(0, 0)), None


def forward_func(apps, schema_editor):
    WorkoutSession = apps.get_model('manager', 'WorkoutSession')

    # Logs pinned to a session of another day must not move the session there
    same_day = Q(logs__date__date=F('date'))
    queryset = WorkoutSession.objects.annotate(
        first_log=Min('logs__date', filter=same_day),
        last_log=Max('logs__date', filter=same_day),
    ).order_by('pk')

    batch = []
    for session in queryset.iterator(chunk_size=BATCH_SIZE):
        session.datetime_start, session.datetime_end = build_interval(session)
        batch.append(session)

        if len(batch) >= BATCH_SIZE:
            WorkoutSession.objects.bulk_update(batch, ['datetime_start', 'datetime_end'])
            batch = []

    if batch:
        WorkoutSession.objects.bulk_update(batch, ['datetime_start', 'datetime_end'])


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0028_backfill_session_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutsession',
            options={'ordering': ['datetime_start']},
        ),
        migrations.RemoveIndex(
            model_name='workoutsession',
            name='manager_wor_routine_224494_idx',
        ),
        migrations.AlterUniqueTogether(
            name='workoutsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='datetime_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date and time'),
        ),
        migrations.AddField(
            model_name='workoutsession',
            name='datetime_start',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Start date and time'
            ),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(
                fields=['routine', 'datetime_start'], name='manager_wor_routine_46e75a_idx'
            ),
        ),
        migrations.RunPython(forward_func, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='workoutsession',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='workoutsession',
            name='time_start',
        ),
    ]
