# Generated by Django 6.0.8 on 2026-09-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('manager', '0029_alter_workoutsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutlog',
            name='routine',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='manager.routine',
                verbose_name='Workout',
            ),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='slot_entry',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.slotentry'
            ),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='day',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.day'
            ),
        ),
        migrations.AlterField(
            model_name='workoutsession',
            name='routine',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sessions',
                to='manager.routine',
            ),
        ),
    ]
