# Generated by Django 5.2.9 on 2025-12-03 18:33

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps

volume_trophy_data = {
    'trophy_type': 'volume',
    'checker_class': 'volume',
    'is_hidden': False,
    'is_progressive': True,
    'is_repeatable': False,
}

workout_count_trophy_data = {
    'trophy_type': 'count',
    'checker_class': 'workout_count_based',
    'is_hidden': False,
    'is_progressive': True,
    'is_repeatable': False,
}

# Define the initial trophies (same as in load_trophies management command)
trophies_data = [
    {
        **workout_count_trophy_data,
        'uuid': '9f1c7c7e-3b2a-4b6f-9b5f-1c3e2d4f5a60',
        'name': 'Beginner',
        'description': 'Complete your first workout',
        'checker_params': {'count': 1},
        'order': 1,
    },
    {
        **workout_count_trophy_data,
        'uuid': '0d2e3f4a-5b6c-47d8-9e0f-1a2b3c4d5e6f',
        'name': 'Consistent',
        'description': 'Complete 10 workouts',
        'checker_params': {'count': 10},
        'is_hidden': False,
        'order': 2,
    },
    {
        **workout_count_trophy_data,
        'uuid': '4b6f9c2d-3e1a-4f5b-8c7d-2e3f4a5b6c7d',
        'name': 'Dedicated',
        'description': 'Complete 50 workouts',
        'checker_params': {'count': 50},
        'order': 3,
    },
    {
        **workout_count_trophy_data,
        'uuid': 'd2c3b4a5-6f7e-48d9-8c0b-2a3c4d5e6f7b',
        'name': 'Obsessed',
        'description': 'Complete 100 workouts',
        'checker_params': {'count': 100},
        'is_hidden': True,
        'order': 4,
    },
    {
        **workout_count_trophy_data,
        'uuid': 'e3f4a5b6-c7d8-49e0-9f1a-2b3c4d5e6f7a',
        'name': 'Legend',
        'description': 'Complete 200 workouts',
        'checker_params': {'count': 200},
        'is_hidden': True,
        'order': 5,
    },
    {
        **workout_count_trophy_data,
        'uuid': 'f4a5b6c7-d8e9-40f1-9a2b-3c4d5e6f7a8b',
        'name': 'Veteran',
        'description': 'Complete 500 workouts',
        'checker_params': {'count': 500},
        'is_hidden': True,
        'order': 6,
    },
    {
        **workout_count_trophy_data,
        'uuid': 'a5b6c7d8-e9f0-41a2-9b3c-4d5e6f7a8b9c',
        'name': 'Titan',
        'description': 'Complete 1000 workouts',
        'checker_params': {'count': 1000},
        'is_hidden': True,
        'order': 7,
    },
    {
        'uuid': 'b605b6a1-953d-41fb-87c9-a2f88b5f5907',
        'name': 'Unstoppable',
        'description': 'Maintain a 30-day workout streak',
        'trophy_type': 'sequence',
        'checker_class': 'streak',
        'checker_params': {'days': 30},
        'is_progressive': True,
        'is_hidden': False,
        'order': 8,
    },
    {
        'uuid': 'bf60e051-a9a5-4bf5-ac4b-1aa713febca7',
        'name': 'Weekend Warrior',
        'description': 'Work out on Saturday and Sunday for 4 consecutive weekends',
        'trophy_type': 'sequence',
        'checker_class': 'weekend_warrior',
        'checker_params': {'weekends': 4},
        'is_progressive': True,
        'is_hidden': False,
        'order': 9,
    },
    {
        **volume_trophy_data,
        'uuid': '5353989b-adc0-481b-a9bc-64365a9179e8',
        'name': 'Elephant lifter',
        'description': 'Lift a cumulative total of 5.000 kg',
        'checker_params': {'kg': 5_000},
        'order': 10,
    },
    {
        **volume_trophy_data,
        'uuid': '3c53887b-feba-4d73-8022-e446f46395c8',
        'name': 'Bus lifter',
        'description': 'Lift a cumulative total of 20.000 kg',
        'checker_params': {'kg': 20_000},
        'order': 11,
    },
    {
        **volume_trophy_data,
        'uuid': '70ee1605-20b8-4c8d-87a1-3787b9b3939d',
        'name': 'Plane lifter',
        'description': 'Lift a cumulative total of 50.000 kg',
        'checker_params': {'kg': 50_000},
        'order': 12,
    },
    {
        **volume_trophy_data,
        'uuid': '3b4521ee-14bc-4a31-a3d8-e6859e183a35',
        'name': 'Blue whale lifter',
        'description': 'Lift a cumulative total of 150.000 kg',
        'checker_params': {'kg': 150_000},
        'is_hidden': True,
        'order': 13,
    },
    {
        **volume_trophy_data,
        'uuid': 'f0a5fd12-2508-4654-89aa-3d6dbb29c7e3',
        'name': 'Space Station lifter',
        'description': 'Lift a cumulative total of 450.000 kg',
        'checker_params': {'kg': 450_000},
        'is_hidden': True,
        'order': 14,
    },
    {
        **volume_trophy_data,
        'uuid': '2c770528-3528-4f0a-9d1a-342d96935bdf',
        'name': 'Millionaire',
        'description': 'Lift a cumulative total of 1.000.000 kg',
        'checker_params': {'kg': 1_000_000},
        'is_hidden': True,
        'order': 15,
    },
    {
        **volume_trophy_data,
        'uuid': 'e414c29d-5828-4ca3-83b5-4837a71ed48f',
        'name': 'Atlas',
        'description': 'Lift a cumulative total of 10.000.000 kg',
        'checker_params': {'kg': 10_000_000},
        'is_hidden': True,
        'order': 16,
    },
    {
        'uuid': 'cc833c0b-1fd9-4cde-baa5-3bff9cd97d0c',
        'name': 'Early Bird',
        'description': 'Complete a workout before 6:00 AM',
        'trophy_type': 'time',
        'checker_class': 'time_based',
        'checker_params': {'before': '06:00'},
        'is_hidden': True,
        'is_progressive': False,
        'order': 17,
    },
    {
        'uuid': '2b00ff1e-69f8-47f0-b8df-976a4127a425',
        'name': 'Night Owl',
        'description': 'Complete a workout after 11:00 PM',
        'trophy_type': 'time',
        'checker_class': 'time_based',
        'checker_params': {'after': '23:00'},
        'is_hidden': True,
        'is_progressive': False,
        'order': 18,
    },
    {
        'uuid': '31a71d9a-bf26-4f18-b82f-afefe6f50df2',
        'name': 'New Year, New Me',
        'description': 'Work out on January 1st',
        'trophy_type': 'date',
        'checker_class': 'date_based',
        'checker_params': {'month': 1, 'day': 1},
        'is_hidden': True,
        'is_progressive': False,
        'order': 19,
    },
    {
        'uuid': '32bb12da-b25f-4e18-81e4-b695eb65283e',
        'name': 'Phoenix',
        'description': 'Return to training after being inactive for 30 days',
        'trophy_type': 'other',
        'checker_class': 'inactivity_return',
        'checker_params': {'inactive_days': 30},
        'is_hidden': True,
        'is_progressive': False,
        'order': 20,
    },
    {
        'uuid': 'd4a5dbe7-7e15-4f7c-8560-a19f5f27eb2e',
        'name': 'Personal Record',
        'description': 'Achieve a new Personal Record on any exercise',
        'trophy_type': 'pr',
        'checker_class': 'personal_record',
        'checker_params': {},
        'is_hidden': True,
        'is_progressive': False,
        'is_repeatable': True,
        'order': 21,
    },
]


def load_initial_trophies(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    """
    Load the initial set of 9 trophies.

    This migration almost idempotent - it will update trophies that already exist
    based on the trophy UUID.
    """
    Trophy = apps.get_model('trophies', 'Trophy')

    for trophy_data in trophies_data:
        Trophy.objects.update_or_create(uuid=trophy_data['uuid'], defaults=trophy_data)


def reverse_load_trophies(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    """
    Reverse migration - delete the initial trophies.

    This is optional and can be left as a no-op if you want to keep
    trophies even when rolling back migrations.
    """
    Trophy = apps.get_model('trophies', 'Trophy')

    trophy_names = [t['name'] for t in trophies_data]

    deleted_count = Trophy.objects.filter(name__in=trophy_names).delete()[0]
    if deleted_count > 0:
        print(f'Trophy migration reverse: Deleted {deleted_count} trophies')


class Migration(migrations.Migration):
    dependencies = [
        ('trophies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_trophies, reverse_load_trophies),
    ]
