# Generated by Django 5.2.9 on 2025-12-03 18:33

from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def load_initial_trophies(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    """
    Load the initial set of 9 trophies.

    This migration almost idempotent - it will update trophies that already exist
    based on the trophy UUID.
    """
    Trophy = apps.get_model('trophies', 'Trophy')

    # Define the initial trophies (same as in load_trophies management command)
    trophies_data = [
        {
            'uuid': '5362e55b-eaf1-4e34-9ef8-661538a3bdd9',
            'name': 'Beginner',
            'description': 'Complete your first workout',
            'trophy_type': 'count',
            'checker_class': 'count_based',
            'checker_params': {'count': 1},
            'is_hidden': False,
            'is_progressive': False,
            'order': 1,
        },
        {
            'uuid': 'b605b6a1-953d-41fb-87c9-a2f88b5f5907',
            'name': 'Unstoppable',
            'description': 'Maintain a 30-day workout streak',
            'trophy_type': 'sequence',
            'checker_class': 'streak',
            'checker_params': {'days': 30},
            'is_hidden': False,
            'is_progressive': True,
            'order': 2,
        },
        {
            'uuid': 'bf60e051-a9a5-4bf5-ac4b-1aa713febca7',
            'name': 'Weekend Warrior',
            'description': 'Work out on Saturday and Sunday for 4 consecutive weekends',
            'trophy_type': 'sequence',
            'checker_class': 'weekend_warrior',
            'checker_params': {'weekends': 4},
            'is_hidden': False,
            'is_progressive': True,
            'order': 3,
        },
        {
            'uuid': '5353989b-adc0-481b-a9bc-64365a9179e8',
            'name': 'Lifter',
            'description': 'Lift a cumulative total of 5,000 kg',
            'trophy_type': 'volume',
            'checker_class': 'volume',
            'checker_params': {'kg': 5000},
            'is_hidden': False,
            'is_progressive': True,
            'order': 4,
        },
        {
            'uuid': '3c53887b-feba-4d73-8022-e446f46395c8',
            'name': 'Atlas',
            'description': 'Lift a cumulative total of 100,000 kg',
            'trophy_type': 'volume',
            'checker_class': 'volume',
            'checker_params': {'kg': 100000},
            'is_hidden': False,
            'is_progressive': True,
            'order': 5,
        },
        {
            'uuid': 'cc833c0b-1fd9-4cde-baa5-3bff9cd97d0c',
            'name': 'Early Bird',
            'description': 'Complete a workout before 6:00 AM',
            'trophy_type': 'time',
            'checker_class': 'time_based',
            'checker_params': {'before': '06:00'},
            'is_hidden': False,
            'is_progressive': False,
            'order': 6,
        },
        {
            'uuid': '2b00ff1e-69f8-47f0-b8df-976a4127a425',
            'name': 'Night Owl',
            'description': 'Complete a workout after 9:00 PM',
            'trophy_type': 'time',
            'checker_class': 'time_based',
            'checker_params': {'after': '21:00'},
            'is_hidden': False,
            'is_progressive': False,
            'order': 7,
        },
        {
            'uuid': '31a71d9a-bf26-4f18-b82f-afefe6f50df2',
            'name': 'New Year, New Me',
            'description': 'Work out on January 1st',
            'trophy_type': 'date',
            'checker_class': 'date_based',
            'checker_params': {'month': 1, 'day': 1},
            'is_hidden': False,
            'is_progressive': False,
            'order': 8,
        },
        {
            'uuid': '32bb12da-b25f-4e18-81e4-b695eb65283e',
            'name': 'Phoenix',
            'description': 'Return to training after being inactive for 30 days',
            'trophy_type': 'other',
            'checker_class': 'inactivity_return',
            'checker_params': {'inactive_days': 30},
            'is_hidden': True,
            'is_progressive': False,
            'order': 9,
        },
    ]

    for trophy_data in trophies_data:
        Trophy.objects.update_or_create(
            name=trophy_data['uuid'],
            defaults=trophy_data
        )

def reverse_load_trophies(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    """
    Reverse migration - delete the initial trophies.

    This is optional and can be left as a no-op if you want to keep
    trophies even when rolling back migrations.
    """
    Trophy = apps.get_model('trophies', 'Trophy')

    trophy_names = [
        'Beginner',
        'Unstoppable',
        'Weekend Warrior',
        'Lifter',
        'Atlas',
        'Early Bird',
        'Night Owl',
        'New Year, New Me',
        'Phoenix',
    ]

    deleted_count = Trophy.objects.filter(name__in=trophy_names).delete()[0]
    if deleted_count > 0:
        print(f'Trophy migration reverse: Deleted {deleted_count} trophies')


class Migration(migrations.Migration):
    dependencies = [
        ('trophies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_trophies, reverse_load_trophies),
    ]
