# Generated by Django 5.2.8 on 2025-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics',
            name='last_complete_weekend_date',
            field=models.DateField(blank=True, help_text='Date of the last Saturday where both Sat and Sun had workouts', null=True, verbose_name='Last complete weekend date'),
        ),
    ]
