# Generated by Django 5.2.9 on 2025-12-03 18:33

from django.db import migrations


def load_initial_trophies(apps, schema_editor):
    """
    Load the initial set of 9 trophies.

    This migration is idempotent - it will skip trophies that already exist
    based on the trophy name.
    """
    Trophy = apps.get_model('trophies', 'Trophy')

    # Define the initial trophies (same as in load_trophies management command)
    trophies_data = [
        {
            'name': 'Beginner',
            'description': 'Complete your first workout',
            'trophy_type': 'count',
            'checker_class': 'count_based',
            'checker_params': {'count': 1},
            'is_hidden': False,
            'is_progressive': False,
            'order': 1,
        },
        {
            'name': 'Unstoppable',
            'description': 'Maintain a 30-day workout streak',
            'trophy_type': 'sequence',
            'checker_class': 'streak',
            'checker_params': {'days': 30},
            'is_hidden': False,
            'is_progressive': True,
            'order': 2,
        },
        {
            'name': 'Weekend Warrior',
            'description': 'Work out on Saturday and Sunday for 4 consecutive weekends',
            'trophy_type': 'sequence',
            'checker_class': 'weekend_warrior',
            'checker_params': {'weekends': 4},
            'is_hidden': False,
            'is_progressive': True,
            'order': 3,
        },
        {
            'name': 'Lifter',
            'description': 'Lift a cumulative total of 5,000 kg',
            'trophy_type': 'volume',
            'checker_class': 'volume',
            'checker_params': {'kg': 5000},
            'is_hidden': False,
            'is_progressive': True,
            'order': 4,
        },
        {
            'name': 'Atlas',
            'description': 'Lift a cumulative total of 100,000 kg',
            'trophy_type': 'volume',
            'checker_class': 'volume',
            'checker_params': {'kg': 100000},
            'is_hidden': False,
            'is_progressive': True,
            'order': 5,
        },
        {
            'name': 'Early Bird',
            'description': 'Complete a workout before 6:00 AM',
            'trophy_type': 'time',
            'checker_class': 'time_based',
            'checker_params': {'before': '06:00'},
            'is_hidden': False,
            'is_progressive': False,
            'order': 6,
        },
        {
            'name': 'Night Owl',
            'description': 'Complete a workout after 9:00 PM',
            'trophy_type': 'time',
            'checker_class': 'time_based',
            'checker_params': {'after': '21:00'},
            'is_hidden': False,
            'is_progressive': False,
            'order': 7,
        },
        {
            'name': 'New Year, New Me',
            'description': 'Work out on January 1st',
            'trophy_type': 'date',
            'checker_class': 'date_based',
            'checker_params': {'month': 1, 'day': 1},
            'is_hidden': False,
            'is_progressive': False,
            'order': 8,
        },
        {
            'name': 'Phoenix',
            'description': 'Return to training after being inactive for 30 days',
            'trophy_type': 'other',
            'checker_class': 'inactivity_return',
            'checker_params': {'inactive_days': 30},
            'is_hidden': True,
            'is_progressive': False,
            'order': 9,
        },
    ]

    created_count = 0
    skipped_count = 0

    for trophy_data in trophies_data:
        # Check if trophy already exists
        if not Trophy.objects.filter(name=trophy_data['name']).exists():
            Trophy.objects.create(**trophy_data)
            created_count += 1
        else:
            skipped_count += 1

    if created_count > 0:
        print(f'Trophy migration: Created {created_count} trophies, skipped {skipped_count}')


def reverse_load_trophies(apps, schema_editor):
    """
    Reverse migration - delete the initial trophies.

    This is optional and can be left as a no-op if you want to keep
    trophies even when rolling back migrations.
    """
    Trophy = apps.get_model('trophies', 'Trophy')

    trophy_names = [
        'Beginner',
        'Unstoppable',
        'Weekend Warrior',
        'Lifter',
        'Atlas',
        'Early Bird',
        'Night Owl',
        'New Year, New Me',
        'Phoenix',
    ]

    deleted_count = Trophy.objects.filter(name__in=trophy_names).delete()[0]
    if deleted_count > 0:
        print(f'Trophy migration reverse: Deleted {deleted_count} trophies')


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0002_add_last_complete_weekend_date'),
    ]

    operations = [
        migrations.RunPython(load_initial_trophies, reverse_load_trophies),
    ]
