# Generated by Django 5.2.9 on 2025-12-16 16:14

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps


def create_personal_record_trophy(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    Trophy = apps.get_model('trophies', 'Trophy')

    if not Trophy.objects.filter(name='Personal Record').exists():
        Trophy.objects.create(
            uuid='d4a5dbe7-7e15-4f7c-8560-a19f5f27eb2e',
            name='Personal Record',
            description='Achieve a new Personal Record on any exercise',
            trophy_type='pr',
            checker_class='personal_record',
            checker_params={},
            is_hidden=True,
            is_progressive=False,
            is_repeatable=True,
            order=10,
        )


def remove_personal_record_trophy(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    Trophy = apps.get_model('trophies', 'Trophy')
    Trophy.objects.filter(name='Personal Record').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('trophies', '0003_load_initial_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='is_repeatable',
            field=models.BooleanField(
                default=False,
                help_text='If true, this trophy can be earned multiple times',
                verbose_name='Repeatable',
            ),
        ),
        migrations.AddField(
            model_name='usertrophy',
            name='context_data',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Additional information concerning this trophy',
                null=True,
                verbose_name='Context data',
            ),
        ),
        migrations.RunPython(create_personal_record_trophy, remove_personal_record_trophy),
    ]
