# Generated by Django 5.2.9 on 2025-12-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trophies', '0003_load_initial_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='If true, this trophy can be earned multiple times', verbose_name='Repeatable'),
        ),
        migrations.AddField(
            model_name='usertrophy',
            name='context_data',
            field=models.JSONField(blank=True, default=None, help_text='Additional information concerning this trophy', null=True, verbose_name='Context data'),
        ),
    ]
