# Generated by Django 5.2.9 on 2025-12-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('trophies', '0003_load_initial_trophies'),
    ]

    def create_personal_record_trophy(apps, schema_editor):
        Trophy = apps.get_model('trophies', 'Trophy')

        if not Trophy.objects.filter(name='Personal Record').exists():
            Trophy.objects.create(
                name='Personal Record',
                description='Repeatable Personal Record (PR) trophy',
                trophy_type='other',
                checker_class='personal_record',
                checker_params={},
                is_hidden=True,
                is_progressive=False,
                is_repeatable=True,
                order=10,
            )

        print(f"Trophy migration: Created trophy 'Personal Record'")

    def remove_personal_record_trophy(apps, schema_editor):
        Trophy = apps.get_model('trophies', 'Trophy')
        Trophy.objects.filter(name='Personal Record').delete()

    operations = [
        migrations.AddField(
            model_name='trophy',
            name='is_repeatable',
            field=models.BooleanField(
                default=False,
                help_text='If true, this trophy can be earned multiple times',
                verbose_name='Repeatable',
            ),
        ),
        migrations.AddField(
            model_name='usertrophy',
            name='context_data',
            field=models.JSONField(
                blank=True,
                default=None,
                help_text='Additional information concerning this trophy',
                null=True,
                verbose_name='Context data',
            ),
        ),
        migrations.RunPython(create_personal_record_trophy, remove_personal_record_trophy),
    ]
