# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-08 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body_measurements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BodyMeasurements',
            new_name='BodyMeasurementsEntry',
        ),
    ]
