name: Build demo Docker image

# Only build when the dockerfile has changed, otherwise scheduled every two weeks
# (on the 1st and 15th every month) since it's not so important to keep this image
# exactly in sync with master
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'extras/docker/demo/Dockerfile'
      - '.github/workflows/docker-demo.yml'
  schedule:
    - cron: '0 6 1,15 * *'

permissions:
  contents: read

jobs:
  demo:
    name: Build demo image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to DockerHub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          push: true
          file: extras/docker/demo/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ vars.REGISTRY_REPO }}/demo:latest,${{ vars.REGISTRY_REPO }}/demo:2.4-dev
